// Command genprobe emits the width-specialized fixed-cell search loops
// of internal/tree (SOW-0027 regression slice H). The probe loop is
// written once below as a template; the emitted functions are per-width
// instantiations (4/8/12/16-byte numeric keys) with the width compile-
// time constant, the target limbs hoisted, and the compare straight-
// line per probe, so each probe is one slot read, one bounds check, and
// one compare - the Go equivalent of Rust's monomorphized lower_bound.
//
// The generic loop in internal/tree/page.go remains for the raw hash
// probe widths (32+ bytes) that compare through CompareRawKey.
//
// Run with: go generate ./internal/tree
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"text/template"
)

// width is one emitted key width: the function name, the numeric width
// used in the upfront geometry guard and the truncated-cell check, the
// hoisted target computation (once, before the loop), the per-probe
// compare declaration, and the equivalent assignment for the final
// exact-match probe.
type width struct {
	Name        string
	Width       int
	Pre         string
	Probe       string // "key, err := search.U32(middle)" (per-probe)
	ProbeTail   string // tail exact-match probe
	Compare     string // "compare := ..." body
	CompareTail string // "compare = ..." body
}

var widths = []width{
	{
		Name:        "U32",
		Width:       4,
		Pre:         "target := key.U32()",
		Probe:       "middleKey, ok := search.U32(middle)",
		ProbeTail:   "lowerKey, ok := search.U32(lower)",
		Compare:     `compare := cmpU32(middleKey, target)`,
		CompareTail: `compare = cmpU32(lowerKey, target)`,
	},
	{
		Name:        "U64",
		Width:       8,
		Pre:         "target := key.U64()",
		Probe:       "middleKey, ok := search.U64(middle)",
		ProbeTail:   "lowerKey, ok := search.U64(lower)",
		Compare:     `compare := cmpU64(middleKey, target)`,
		CompareTail: `compare = cmpU64(lowerKey, target)`,
	},
	{
		Name:      "U64U32",
		Width:     12,
		Pre:       "targetHi := key.U64()\n\ttargetLo := beU32(key.data[8:12])",
		Probe:     "middleHi, middleLo, ok := search.U64U32(middle)",
		ProbeTail: "lowerHi, lowerLo, ok := search.U64U32(lower)",
		Compare: `compare := cmpU64(middleHi, targetHi)
		if compare == 0 {
			compare = cmpU32(middleLo, targetLo)
		}`,
		CompareTail: `compare = cmpU64(lowerHi, targetHi)
		if compare == 0 {
			compare = cmpU32(lowerLo, targetLo)
		}`,
	},
	{
		Name:      "U128",
		Width:     16,
		Pre:       "targetHi, targetLo := key.U128()",
		Probe:     "middleHi, middleLo, ok := search.U128(middle)",
		ProbeTail: "lowerHi, lowerLo, ok := search.U128(lower)",
		// The wire u128 cell keeps the low limb at offset 0 and the
		// high limb at offset 8 (format.U128/PutU128); the probe must
		// decode through format.U128, never raw limb order.
		Compare:     `compare := cmpU128(middleHi, middleLo, targetHi, targetLo)`,
		CompareTail: `compare = cmpU128(lowerHi, lowerLo, targetHi, targetLo)`,
	},
}

// bodyTemplate is the single authoritative search-loop shape. Every
// width instantiates the same loop; only the geometry guard, the hoisted
// targets, the truncated-cell check, and the compare differ.
var bodyTemplate = template.Must(template.New("body").Parse(`func fixedLowerBound{{ .Name }}(page []byte, header *Header, cellLen int, key Key, insertion bool) (int, bool, error) {
	if cellLen < {{ .Width }} {
		return 0, false, corrupt("fixed slotted-page search shape is invalid")
	}
	{{ .Pre }}
	search, err := format.NewFixedSearch(page, *header, cellLen)
	if err != nil {
		return 0, false, corrupt("fixed slotted-page search shape is invalid")
	}
	lower := 0
	upper := int(header.ItemCount)
	lastCompare := 0
	lastIndex := -1
	for lower < upper {
		middle := lower + (upper-lower)/2
		work.KeyProbe(1)
		{{ .Probe }}
		if !ok {
			return 0, false, corrupt("slotted-page cell is outside the record area")
		}
		{{ .Compare }}
		lastCompare = compare
		lastIndex = middle
		if compare < 0 {
			lower = middle + 1
		} else {
			upper = middle
		}
	}
	exists := false
	if lower < int(header.ItemCount) {
		compare := lastCompare
		if lastIndex != lower {
			work.KeyProbe(1)
			{{ .ProbeTail }}
			if !ok {
				return 0, false, corrupt("slotted-page cell is outside the record area")
			}
			{{ .CompareTail }}
		}
		exists = compare == 0
	}
	if insertion || exists || lower == 0 {
		return lower, exists, nil
	}
	return lower - 1, false, nil
}
`))

func main() {
	var out bytes.Buffer
	out.WriteString("// Code generated by genprobe; DO NOT EDIT.\n")
	out.WriteString("//\n")
	out.WriteString("// Width-specialized fixed-cell search loops (SOW-0027 regression\n")
	out.WriteString("// slice H): one materialized loop per numeric key width (4/8/12/16\n")
	out.WriteString("// bytes) with the compare inlined and the target limbs hoisted,\n")
	out.WriteString("// mirroring Rust's monomorphized per-key lower_bound. The single\n")
	out.WriteString("// authoritative loop source is internal/tree/genprobe; edit the\n")
	out.WriteString("// generator, not this file.\n")
	out.WriteString("\n")
	out.WriteString("package tree\n")
	out.WriteString("\n")
	out.WriteString("import (\n")
	out.WriteString("\t\"github.com/firehol/iprange/v4/go/internal/format\"\n")
	out.WriteString("\t\"github.com/firehol/iprange/v4/go/internal/work\"\n")
	out.WriteString(")\n")
	for _, w := range widths {
		fmt.Fprintf(&out, "\n// fixedLowerBound%s is the %d-byte %s search loop\n", w.Name, w.Width, w.Name)
		out.WriteString("// (Rust fixed_tree/page.rs lower_bound with an inlined key_at). The\n")
		out.WriteString("// target limbs are hoisted before the loop and the compare is\n")
		out.WriteString("// straight-line per probe.\n")
		if err := bodyTemplate.Execute(&out, w); err != nil {
			fmt.Fprintln(os.Stderr, "genprobe:", err)
			os.Exit(1)
		}
	}
	// Normalize the emission through go/format so the generated file is
	// always gofmt-stable and `go generate` is idempotent.
	src, err := format.Source(out.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, "genprobe: go/format:", err)
		os.Exit(1)
	}
	target := resolveTarget()
	if err := os.WriteFile(target, src, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "genprobe:", err)
		os.Exit(1)
	}
	fmt.Println("genprobe: wrote", target)
}

// resolveTarget places the emitted file next to the package regardless
// of whether the generator runs from the package directory (go generate)
// or from the module root (go run ./internal/tree/genprobe).
func resolveTarget() string {
	target := "probe_widths.go"
	if base := filepath.Base(mustCwd()); base != "tree" {
		target = filepath.Join("internal", "tree", "probe_widths.go")
	}
	return target
}

func mustCwd() string {
	dir, err := os.Getwd()
	if err != nil {
		fmt.Fprintln(os.Stderr, "genprobe:", err)
		os.Exit(1)
	}
	return dir
}
