// Code generated by genprobe; DO NOT EDIT.
//
// Width-specialized fixed-cell search loops (SOW-0027 regression
// slice H): one materialized loop per numeric key width (4/8/12/16
// bytes) with the compare inlined and the target limbs hoisted,
// mirroring Rust's monomorphized per-key lower_bound. The single
// authoritative loop source is internal/tree/genprobe; edit the
// generator, not this file.

package tree

import (
	"github.com/firehol/iprange/v4/go/internal/format"
	"github.com/firehol/iprange/v4/go/internal/work"
)

// fixedLowerBoundU32 is the 4-byte U32 search loop
// (Rust fixed_tree/page.rs lower_bound with an inlined key_at). The
// target limbs are hoisted before the loop and the compare is
// straight-line per probe.
func fixedLowerBoundU32(page []byte, header *Header, cellLen int, key Key, insertion bool, validate func(cell []byte) error) (int, bool, error) {
	if cellLen < 4 {
		return 0, false, corrupt("fixed slotted-page search shape is invalid")
	}
	target := key.U32()
	search, err := format.NewFixedSearch(page, *header, cellLen)
	if err != nil {
		return 0, false, corrupt("fixed slotted-page search shape is invalid")
	}
	lower := 0
	upper := int(header.ItemCount)
	lastCompare := 0
	lastIndex := -1
	for lower < upper {
		middle := lower + (upper-lower)/2
		work.KeyProbe(1)
		cell, err := search.Cell(middle)
		if err != nil {
			return 0, false, corrupt("slotted-page cell is outside the record area")
		}
		if validate != nil {
			if err := validate(cell); err != nil {
				return 0, false, err
			}
		}
		if len(cell) < 4 {
			return 0, false, corrupt("tree key is truncated")
		}
		compare := cmpU32(format.U32(cell), target)
		lastCompare = compare
		lastIndex = middle
		if compare < 0 {
			lower = middle + 1
		} else {
			upper = middle
		}
	}
	exists := false
	if lower < int(header.ItemCount) {
		compare := lastCompare
		if lastIndex != lower {
			work.KeyProbe(1)
			cell, err := search.Cell(lower)
			if err != nil {
				return 0, false, corrupt("slotted-page cell is outside the record area")
			}
			if validate != nil {
				if err := validate(cell); err != nil {
					return 0, false, err
				}
			}
			if len(cell) < 4 {
				return 0, false, corrupt("tree key is truncated")
			}
			compare = cmpU32(format.U32(cell), target)
		}
		exists = compare == 0
	}
	if insertion || exists || lower == 0 {
		return lower, exists, nil
	}
	return lower - 1, false, nil
}

// fixedLowerBoundU64 is the 8-byte U64 search loop
// (Rust fixed_tree/page.rs lower_bound with an inlined key_at). The
// target limbs are hoisted before the loop and the compare is
// straight-line per probe.
func fixedLowerBoundU64(page []byte, header *Header, cellLen int, key Key, insertion bool, validate func(cell []byte) error) (int, bool, error) {
	if cellLen < 8 {
		return 0, false, corrupt("fixed slotted-page search shape is invalid")
	}
	target := key.U64()
	search, err := format.NewFixedSearch(page, *header, cellLen)
	if err != nil {
		return 0, false, corrupt("fixed slotted-page search shape is invalid")
	}
	lower := 0
	upper := int(header.ItemCount)
	lastCompare := 0
	lastIndex := -1
	for lower < upper {
		middle := lower + (upper-lower)/2
		work.KeyProbe(1)
		cell, err := search.Cell(middle)
		if err != nil {
			return 0, false, corrupt("slotted-page cell is outside the record area")
		}
		if validate != nil {
			if err := validate(cell); err != nil {
				return 0, false, err
			}
		}
		if len(cell) < 8 {
			return 0, false, corrupt("tree key is truncated")
		}
		compare := cmpU64(format.U64(cell), target)
		lastCompare = compare
		lastIndex = middle
		if compare < 0 {
			lower = middle + 1
		} else {
			upper = middle
		}
	}
	exists := false
	if lower < int(header.ItemCount) {
		compare := lastCompare
		if lastIndex != lower {
			work.KeyProbe(1)
			cell, err := search.Cell(lower)
			if err != nil {
				return 0, false, corrupt("slotted-page cell is outside the record area")
			}
			if validate != nil {
				if err := validate(cell); err != nil {
					return 0, false, err
				}
			}
			if len(cell) < 8 {
				return 0, false, corrupt("tree key is truncated")
			}
			compare = cmpU64(format.U64(cell), target)
		}
		exists = compare == 0
	}
	if insertion || exists || lower == 0 {
		return lower, exists, nil
	}
	return lower - 1, false, nil
}

// fixedLowerBoundU64U32 is the 12-byte U64U32 search loop
// (Rust fixed_tree/page.rs lower_bound with an inlined key_at). The
// target limbs are hoisted before the loop and the compare is
// straight-line per probe.
func fixedLowerBoundU64U32(page []byte, header *Header, cellLen int, key Key, insertion bool, validate func(cell []byte) error) (int, bool, error) {
	if cellLen < 12 {
		return 0, false, corrupt("fixed slotted-page search shape is invalid")
	}
	targetHi := key.U64()
	targetLo := beU32(key.data[8:12])
	search, err := format.NewFixedSearch(page, *header, cellLen)
	if err != nil {
		return 0, false, corrupt("fixed slotted-page search shape is invalid")
	}
	lower := 0
	upper := int(header.ItemCount)
	lastCompare := 0
	lastIndex := -1
	for lower < upper {
		middle := lower + (upper-lower)/2
		work.KeyProbe(1)
		cell, err := search.Cell(middle)
		if err != nil {
			return 0, false, corrupt("slotted-page cell is outside the record area")
		}
		if validate != nil {
			if err := validate(cell); err != nil {
				return 0, false, err
			}
		}
		if len(cell) < 12 {
			return 0, false, corrupt("tree key is truncated")
		}
		compare := cmpU64(format.U64(cell), targetHi)
		if compare == 0 {
			compare = cmpU32(format.U32(cell[8:12]), targetLo)
		}
		lastCompare = compare
		lastIndex = middle
		if compare < 0 {
			lower = middle + 1
		} else {
			upper = middle
		}
	}
	exists := false
	if lower < int(header.ItemCount) {
		compare := lastCompare
		if lastIndex != lower {
			work.KeyProbe(1)
			cell, err := search.Cell(lower)
			if err != nil {
				return 0, false, corrupt("slotted-page cell is outside the record area")
			}
			if validate != nil {
				if err := validate(cell); err != nil {
					return 0, false, err
				}
			}
			if len(cell) < 12 {
				return 0, false, corrupt("tree key is truncated")
			}
			compare = cmpU64(format.U64(cell), targetHi)
			if compare == 0 {
				compare = cmpU32(format.U32(cell[8:12]), targetLo)
			}
		}
		exists = compare == 0
	}
	if insertion || exists || lower == 0 {
		return lower, exists, nil
	}
	return lower - 1, false, nil
}

// fixedLowerBoundU128 is the 16-byte U128 search loop
// (Rust fixed_tree/page.rs lower_bound with an inlined key_at). The
// target limbs are hoisted before the loop and the compare is
// straight-line per probe.
func fixedLowerBoundU128(page []byte, header *Header, cellLen int, key Key, insertion bool, validate func(cell []byte) error) (int, bool, error) {
	if cellLen < 16 {
		return 0, false, corrupt("fixed slotted-page search shape is invalid")
	}
	targetHi, targetLo := key.U128()
	search, err := format.NewFixedSearch(page, *header, cellLen)
	if err != nil {
		return 0, false, corrupt("fixed slotted-page search shape is invalid")
	}
	lower := 0
	upper := int(header.ItemCount)
	lastCompare := 0
	lastIndex := -1
	for lower < upper {
		middle := lower + (upper-lower)/2
		work.KeyProbe(1)
		cell, err := search.Cell(middle)
		if err != nil {
			return 0, false, corrupt("slotted-page cell is outside the record area")
		}
		if validate != nil {
			if err := validate(cell); err != nil {
				return 0, false, err
			}
		}
		if len(cell) < 16 {
			return 0, false, corrupt("tree key is truncated")
		}
		hi, lo := format.U128(cell)
		compare := cmpU128(hi, lo, targetHi, targetLo)
		lastCompare = compare
		lastIndex = middle
		if compare < 0 {
			lower = middle + 1
		} else {
			upper = middle
		}
	}
	exists := false
	if lower < int(header.ItemCount) {
		compare := lastCompare
		if lastIndex != lower {
			work.KeyProbe(1)
			cell, err := search.Cell(lower)
			if err != nil {
				return 0, false, corrupt("slotted-page cell is outside the record area")
			}
			if validate != nil {
				if err := validate(cell); err != nil {
					return 0, false, err
				}
			}
			if len(cell) < 16 {
				return 0, false, corrupt("tree key is truncated")
			}
			hi, lo := format.U128(cell)
			compare = cmpU128(hi, lo, targetHi, targetLo)
		}
		exists = compare == 0
	}
	if insertion || exists || lower == 0 {
		return lower, exists, nil
	}
	return lower - 1, false, nil
}
