// Code generated by genfamilies; DO NOT EDIT.
//
// Family-specialized gap/replace layer (SOW-0027 regression slices
// I-1b and I-2): the concrete 4-byte RangeCodec4 probe,
// selector, descent, replacement application, and tree entries with the
// codec calls inlined, mirroring Rust's monomorphized fixed_tree/gap.rs
// over RangeCodec<Ipv4Key>/Ipv6Key. The single authoritative source is
// internal/tree/genfamilies; edit the generator, not this file.

package tree

import (
	"github.com/firehol/iprange/v4/go/internal/format"
	"github.com/firehol/iprange/v4/go/internal/work"
)

// rangeProbe4 is the concrete RangeCodec4 local-gap probe
// (Rust PrivateGap<RangeCodec<IpvXKey>>): every family operation is a
// direct call on the concrete codec, so one probe never dispatches
// through an interface.
type rangeProbe4 struct {
	codec RangeCodec4
	r     RangeRecord[RangeKey4]
}

func (g rangeProbe4) decode(cell []byte) (RangeRecord[RangeKey4], error) {
	return g.codec.ReadLeaf(cell)
}

// Previous implements the LocalGap probe by value (Rust
// LocalGap::previous): a Reject decision carries the already-decoded
// record (Rust LocalPrevious::Reject(previous)), so the selector never
// re-decodes the probing cell.
func (g rangeProbe4) Previous(exact bool, cell []byte) (LocalPrevious, RangeRecord[RangeKey4], error) {
	if cell == nil {
		return LocalPreviousAccept, RangeRecord[RangeKey4]{}, nil
	}
	previous, err := g.decode(cell)
	if err != nil {
		return 0, RangeRecord[RangeKey4]{}, err
	}
	bridges := false
	if next, ok := g.codec.Next(previous.To); ok {
		bridges = g.codec.Equal(next, g.r.From)
	}
	if exact || !g.codec.Less(previous.To, g.r.From) ||
		(previous.Value == g.r.Value && bridges) {
		return LocalPreviousReject, previous, nil
	}
	return LocalPreviousAccept, RangeRecord[RangeKey4]{}, nil
}

// Next implements the LocalGap probe by value (Rust LocalGap::next).
func (g rangeProbe4) Next(cell []byte) (LocalNext, RangeRecord[RangeKey4], error) {
	if cell == nil {
		return LocalNextAccept, RangeRecord[RangeKey4]{}, nil
	}
	next, err := g.decode(cell)
	if err != nil {
		return 0, RangeRecord[RangeKey4]{}, err
	}
	bridges := false
	if boundary, ok := g.codec.Next(g.r.To); ok {
		bridges = g.codec.Equal(boundary, next.From)
	}
	if g.codec.Less(g.r.To, next.From) && (next.Value != g.r.Value || !bridges) {
		return LocalNextAccept, RangeRecord[RangeKey4]{}, nil
	}
	return LocalNextReject, next, nil
}

// gapSelector4 is the concrete RangeCodec4 gap selector
// (Rust GapSelector<RangeCodec<IpvXKey>, PrivateGap<...>>).
type gapSelector4 struct {
	codec   RangeCodec4
	key     Key
	cellLen int
	gap     rangeProbe4
}

// selectAt decides the gap at one already-located position (Rust
// GapSelector::select_at).
func (g *gapSelector4) selectAt(page []byte, header Header, path *Path, index int, exists bool) (gapDecision[RangeRecord[RangeKey4]], error) {
	predecessor, predecessorComplete, err := g.probePredecessor(page, header, path, index, exists)
	if err != nil {
		return gapDecision[RangeRecord[RangeKey4]]{}, err
	}
	successor, successorComplete, err := g.probeSuccessor(page, header, path, index, exists)
	if err != nil {
		return gapDecision[RangeRecord[RangeKey4]]{}, err
	}
	if predecessor.valid || successor.valid || !predecessorComplete || !successorComplete {
		return gapDecision[RangeRecord[RangeKey4]]{
			insert:              false,
			index:               index,
			predecessor:         predecessor,
			successor:           successor,
			predecessorComplete: predecessorComplete,
			successorComplete:   successorComplete,
		}, nil
	}
	return gapDecision[RangeRecord[RangeKey4]]{insert: true, index: index, fits: format.SlottedInsertFits(&header, g.cellLen)}, nil
}

func (g *gapSelector4) probePredecessor(page []byte, header Header, path *Path, index int, exists bool) (rejectCell[RangeRecord[RangeKey4]], bool, error) {
	if exists {
		cell, err := g.validLeaf(page, header, index)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		decision, value, err := g.gap.Previous(true, cell)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		if decision == LocalPreviousAccept {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, corrupt("exact B+tree key was accepted as a gap")
		}
		return rejectCell[RangeRecord[RangeKey4]]{index: index, value: value, valid: true}, true, nil
	}
	if index > 0 {
		cell, err := g.validLeaf(page, header, index-1)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		decision, value, err := g.gap.Previous(false, cell)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		if decision == LocalPreviousAccept {
			return rejectCell[RangeRecord[RangeKey4]]{}, true, nil
		}
		return rejectCell[RangeRecord[RangeKey4]]{index: index - 1, value: value, valid: true}, true, nil
	}
	if allFirst(path) {
		decision, _, err := g.gap.Previous(false, nil)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		if decision == LocalPreviousReject {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, corrupt("absent B+tree predecessor was rejected")
		}
		return rejectCell[RangeRecord[RangeKey4]]{}, true, nil
	}
	return rejectCell[RangeRecord[RangeKey4]]{}, false, nil
}

func (g *gapSelector4) probeSuccessor(page []byte, header Header, path *Path, index int, exists bool) (rejectCell[RangeRecord[RangeKey4]], bool, error) {
	successorIndex := index
	if exists {
		successorIndex++
	}
	if successorIndex < int(header.ItemCount) {
		cell, err := g.validLeaf(page, header, successorIndex)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		decision, value, err := g.gap.Next(cell)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		if decision == LocalNextAccept {
			return rejectCell[RangeRecord[RangeKey4]]{}, true, nil
		}
		return rejectCell[RangeRecord[RangeKey4]]{index: successorIndex, value: value, valid: true}, true, nil
	}
	if allLast(path) {
		decision, _, err := g.gap.Next(nil)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		if decision == LocalNextReject {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, corrupt("absent B+tree successor was rejected")
		}
		return rejectCell[RangeRecord[RangeKey4]]{}, true, nil
	}
	return rejectCell[RangeRecord[RangeKey4]]{}, false, nil
}

// validLeaf re-verifies one leaf cell through the concrete codec (Rust
// validated_leaf): one SlottedCell read plus one ReadLeaf decode, no
// interface dispatch and no second decode anywhere else on the probe.
func (g gapSelector4) validLeaf(page []byte, header Header, index int) ([]byte, error) {
	cell, err := format.SlottedCell(page, &header, index, g.codec.LeafSize())
	if err != nil {
		return nil, corrupt("slotted-page cell is outside the record area")
	}
	if _, err := g.codec.ReadLeaf(cell); err != nil {
		return nil, err
	}
	return cell, nil
}

// rangeCellSize4 is the fixed cell size of one
// RangeCodec4 tree level (Rust FixedCellSize): the range record on
// leaves, the key-plus-child entry on branches.
func rangeCellSize4(level uint16) int {
	if level == 0 {
		return format.RangeRecordV4Size
	}
	return 4 + 4
}

// parseRange4 validates one slotted page of the family (the
// inlined form of parse: leaf/branch type and aux are family constants,
// so the type and discriminator checks fold to two compares).
func parseRange4(page []byte, selectedTxn uint64, expectedLevel uint16, checkLevel bool) (Header, error) {
	work.PageParse(1)
	h, err := format.ParseTreeHeader(page, selectedTxn, format.PageTypeRangeBranch, format.PageTypeRangeLeaf, uint32(format.AddressFamilyIPv4), expectedLevel, checkLevel)
	if err != nil {
		return Header{}, corrupt("slotted-page header is invalid: " + err.Error())
	}
	return h, nil
}

// branchChild4 reads the child page number of one branch
// entry (the inlined form of branchChild: the entry is a fixed
// key-plus-child cell whose width is a family constant).
func branchChild4(page []byte, header *Header, index int, pageLimit uint64) (uint32, error) {
	cell, err := format.SlottedCell(page, header, index, 4+4)
	if err != nil {
		return 0, corrupt("slotted-page cell is outside the record area")
	}
	child := format.U32(cell[4:])
	if child < 2 || uint64(child) >= pageLimit {
		return 0, corrupt("B+tree child page is invalid")
	}
	return child, nil
}

// replaceBranchChild4 rewrites one branch slot to name a new
// child page (the inlined form of replaceBranchChild: the replacement
// entry is the old key bytes plus the new child number).
func replaceBranchChild4(store Store, pageNumber uint32, index int, child uint32) error {
	targetTxn := store.TargetTxn()
	page, err := store.Inspect(pageNumber)
	if err != nil {
		return err
	}
	header, err := parseRange4(page, targetTxn, 0, false)
	if err != nil {
		return err
	}
	cell, err := format.SlottedCell(page, &header, index, 4+4)
	if err != nil {
		return corrupt("slotted-page cell is outside the record area")
	}
	oldLen := len(cell)
	if _, err := branchChild4(page, &header, index, store.PageLimit()); err != nil {
		return err
	}
	var replacement [4 + 4]byte
	copy(replacement[:4], cell[:4])
	format.PutU32(replacement[4:], child)
	page, tag, err := store.Update(pageNumber)
	if err != nil {
		return err
	}
	ok, err := format.SlottedReplace(page, &header, index, oldLen, replacement[:])
	if err != nil {
		return err
	}
	if !ok {
		return corrupt("B+tree child replacement no longer fits")
	}
	return store.RestoreDirty(pageNumber, tag)
}

// privateRangePath4 descends from the root, privatizing every
// committed page along the path (the inlined form of privatePathSelect:
// page validation, the fixed-key search, and the branch-child decode are
// family constants; the COW touch stays shared).
func privateRangePath4(store Store, root *uint32, key Key, retired RetiredPages, leaf *PrivateLeaf) (RetiredPages, error) {
	work.TreeLookup(1)
	var path Path
	pageNumber := *root
	var expectedLevel uint16
	checkLevel := false
	hasParent := false
	parentPage := uint32(0)
	parentIndex := 0

	for {
		page, err := store.Inspect(pageNumber)
		if err != nil {
			return retired, err
		}
		header, err := parseRange4(page, store.TargetTxn(), expectedLevel, checkLevel)
		if err != nil {
			return retired, err
		}
		born := format.U64(page[format.HeaderBorn:])
		if header.Level == 0 {
			activePage := pageNumber
			if born != store.TargetTxn() {
				copied, err := touch(store, pageNumber, &retired)
				if err != nil {
					return retired, err
				}
				activePage = copied
				if hasParent {
					if err := replaceBranchChild4(store, parentPage, parentIndex, copied); err != nil {
						return retired, err
					}
				} else {
					*root = copied
				}
				// The leaf moved to a fresh private page; re-inspect it.
				// The private page view is required for the caller's
				// selection, and the source mapping view may be a growth
				// or COW buffer the draft no longer owns.
				if page, err = store.Inspect(copied); err != nil {
					return retired, err
				}
				if header, err = parseRange4(page, store.TargetTxn(), expectedLevel, checkLevel); err != nil {
					return retired, err
				}
			}
			*leaf = PrivateLeaf{Path: path, PageNumber: activePage, Header: header, Page: page}
			return retired, nil
		}
		index, _, err := fixedLowerBoundU32(page, &header, rangeCellSize4(header.Level), key, false)
		if err != nil {
			return retired, err
		}
		child, err := branchChild4(page, &header, index, store.PageLimit())
		if err != nil {
			return retired, err
		}
		activePage := pageNumber
		if born != store.TargetTxn() {
			copied, err := touch(store, pageNumber, &retired)
			if err != nil {
				return retired, err
			}
			activePage = copied
			if hasParent {
				if err := replaceBranchChild4(store, parentPage, parentIndex, copied); err != nil {
					return retired, err
				}
			} else {
				*root = copied
			}
		}
		if err := path.Push(Frame{PageNumber: activePage, Index: index, ItemCount: int(header.ItemCount)}); err != nil {
			return retired, err
		}
		hasParent = true
		parentPage = activePage
		parentIndex = index
		pageNumber = child
		expectedLevel = header.Level - 1
		checkLevel = true
		work.TreeDescent(1)
	}
}

// replacementFits4 reports whether a 2-3 cell replacement
// fits in one leaf (the inlined form of replacementFits: the replaced
// cell width is a family constant).
func replacementFits4(page []byte, header *Header, edit Replacement) (bool, error) {
	work.EditFitProbe(1)
	if edit.index >= int(header.ItemCount) || len(edit.cells) == 0 {
		return false, corrupt("B+tree replacement is invalid")
	}
	oldCell, err := format.SlottedCell(page, header, edit.index, rangeCellSize4(header.Level))
	if err != nil {
		return false, corrupt("slotted-page cell is outside the record area")
	}
	available := len(oldCell) + int(header.Upper-header.Lower)
	payload := 0
	for _, cell := range edit.cells {
		payload += len(cell)
	}
	required := payload + (len(edit.cells)-1)*2
	return required <= available, nil
}

// applyCells4 applies one 2-3 cell replacement to a private
// leaf (the inlined form of applyCells: parse and cell widths are
// family constants).
func applyCells4(page []byte, header *Header, index int, cells [][]byte) error {
	oldCell, err := format.SlottedCell(page, header, index, rangeCellSize4(header.Level))
	if err != nil {
		return corrupt("slotted-page cell is outside the record area")
	}
	ok, err := format.SlottedReplace(page, header, index, len(oldCell), cells[0])
	if err != nil {
		return err
	}
	if !ok {
		return corrupt("B+tree replacement no longer fits")
	}
	for offset, cell := range cells[1:] {
		current, err := parseRange4(page, ^uint64(0), header.Level, true)
		if err != nil {
			return err
		}
		ok, err := format.SlottedInsert(page, &current, index+offset+1, cell)
		if err != nil {
			return err
		}
		if !ok {
			return corrupt("B+tree replacement insertion no longer fits")
		}
	}
	return nil
}

// applyReplacement4 applies one leaf replacement, splitting
// when it does not fit (the inlined form of applyReplacement; the rare
// split path keeps the generic reference machinery).
func applyReplacement4(codec RangeCodec4, store Store, pageNumber uint32, header *Header, edit Replacement) (branchSplit, bool, error) {
	page, err := store.Inspect(pageNumber)
	if err != nil {
		return branchSplit{}, false, err
	}
	fits, err := replacementFits4(page, header, edit)
	if err != nil {
		return branchSplit{}, false, err
	}
	if fits {
		page, tag, err := store.Update(pageNumber)
		if err != nil {
			return branchSplit{}, false, err
		}
		if err := applyCells4(page, header, edit.index, edit.cells); err != nil {
			return branchSplit{}, false, err
		}
		return branchSplit{}, false, store.RestoreDirty(pageNumber, tag)
	}
	return splitReplacement4(codec, store, pageNumber, header, edit)
}

// replaceTarget4 replaces one leaf cell with 2-3 cells and
// propagates the resulting split (the inlined form of replaceTarget;
// the split path keeps the generic propagation).
func replaceTarget4(codec RangeCodec4, store Store, root *uint32, target LeafTarget, cells [][]byte) error {
	edit := Replacement{index: target.Index, cells: cells}
	split, ok, err := applyReplacement4(codec, store, target.PageNumber, &target.Header, edit)
	if err != nil {
		return err
	}
	if !ok {
		return nil
	}
	if split.level != 0 {
		return corrupt("B+tree leaf replacement changed level")
	}
	return propagateSplit(codec, store, root, &target.Path, target.PageNumber, split.leftFirst, split.rightPage, split.rightFirst, 0)
}

// requireLeaf4 validates one leaf cell of the family (the
// inlined form of RequireLeaf: the leaf size is a family constant and
// the decode is a direct concrete codec call, so the probe never
// re-interfaces the codec or consults MaxLeafSize).
func requireLeaf4(codec RangeCodec4, leafCell []byte) error {
	if len(leafCell) == 0 || len(leafCell) > format.RangeRecordV4Size {
		return invalid("wrong B+tree leaf size")
	}
	work.LeafValidation(1)
	_, err := codec.ReadLeaf(leafCell)
	return err
}

// codecCell4 reads one fixed-cell slot of the family (the
// inlined form of codecCell: the cell width is a family constant, so
// the fixed slotted read is direct and the error maps identically).
func codecCell4(page []byte, header *Header, index int) ([]byte, error) {
	cell, err := format.SlottedCell(page, header, index, rangeCellSize4(header.Level))
	if err != nil {
		return nil, corrupt("slotted-page cell is outside the record area")
	}
	return cell, nil
}

// truncate4 keeps the first keep logical records of one
// fixed-cell page (the inlined form of truncate: the fixed path with the
// family cell width).
func truncate4(page []byte, header *Header, keep int) (Header, error) {
	shape, err := format.SlottedTruncateFixed(page, header, keep, rangeCellSize4(header.Level))
	if err != nil {
		return Header{}, corrupt(err.Error())
	}
	return shapeHeader(header, shape), nil
}

// replacementCell4 maps one virtual index to a replacement
// cell or an existing fixed cell (the inlined form of replacementCell).
func replacementCell4(source []byte, header *Header, edit Replacement, index int) ([]byte, error) {
	if offset := index - edit.index; offset >= 0 && offset < len(edit.cells) {
		return edit.cells[offset], nil
	}
	sourceIndex := index
	if index >= edit.index+len(edit.cells) {
		sourceIndex = index - len(edit.cells) + 1
	}
	return codecCell4(source, header, sourceIndex)
}

// buildReplacement4 builds one fresh page from a source page
// and one replacement over [start, end) (the inlined form of
// buildReplacement: page type, aux, and cell widths are family
// constants).
func buildReplacement4(source []byte, header *Header, edit Replacement, start, end int, output []byte) error {
	pageType := format.PageTypeRangeLeaf
	if header.Level != 0 {
		pageType = format.PageTypeRangeBranch
	}
	b := format.NewSlottedBuilder(output, pageType, format.U64(source[format.HeaderBorn:]), header.Level, uint32(format.AddressFamilyIPv4))
	for index := start; index < end; index++ {
		cell, err := replacementCell4(source, header, edit, index)
		if err != nil {
			return err
		}
		if err := b.Push(output, cell); err != nil {
			return corrupt("B+tree page build failed: " + err.Error())
		}
	}
	return b.Finish(output)
}

// replacementSplitIndex4 picks the split point of one fixed
// cell replacement (the inlined form of replacementSplitIndex: ranges
// are always fixed cells, so the width-based midpoint is direct).
func replacementSplitIndex4(header *Header, edit Replacement) (int, error) {
	return fixedSplitIndex(edit.total(int(header.ItemCount)), rangeCellSize4(header.Level))
}

// keepLeftReplacement4 keeps the left side of one split
// replacement on the original page (the inlined form of
// keepLeftReplacement).
func keepLeftReplacement4(store Store, pageNumber uint32, header *Header, edit Replacement, middle int) error {
	page, tag, err := store.Update(pageNumber)
	if err != nil {
		return err
	}
	if middle <= edit.index {
		_, err := truncate4(page, header, middle)
		if err != nil {
			return err
		}
		return store.RestoreDirty(pageNumber, tag)
	}
	if middle < edit.index+len(edit.cells) {
		left, err := truncate4(page, header, edit.index+1)
		if err != nil {
			return err
		}
		if err := applyCells4(page, &left, edit.index, edit.cells[:middle-edit.index]); err != nil {
			return err
		}
		return store.RestoreDirty(pageNumber, tag)
	}
	keep := middle - (len(edit.cells) - 1)
	left, err := truncate4(page, header, keep)
	if err != nil {
		return err
	}
	if err := applyCells4(page, &left, edit.index, edit.cells); err != nil {
		return err
	}
	return store.RestoreDirty(pageNumber, tag)
}

// firstKey4 reads the first key of one family page (the
// inlined form of FirstKey: page validation and the first cell read are
// family constants).
func firstKey4(codec RangeCodec4, store Store, pageNumber uint32, level uint16) (Key, error) {
	targetTxn := store.TargetTxn()
	page, err := store.Inspect(pageNumber)
	if err != nil {
		return Key{}, err
	}
	header, err := parseRange4(page, targetTxn, level, true)
	if err != nil {
		return Key{}, err
	}
	cell, err := codecCell4(page, &header, 0)
	if err != nil {
		return Key{}, err
	}
	return codec.ReadKey(cell, header.Level)
}

// splitReplacement4 splits one leaf replacement across two
// pages (the inlined form of splitReplacement: split index, page build,
// left keep, and both first keys use the family-specialized helpers).
func splitReplacement4(codec RangeCodec4, store Store, pageNumber uint32, header *Header, edit Replacement) (branchSplit, bool, error) {
	total := edit.total(int(header.ItemCount))
	middle, err := replacementSplitIndex4(header, edit)
	if err != nil {
		return branchSplit{}, false, err
	}
	rightPage, err := store.Allocate()
	if err != nil {
		return branchSplit{}, false, err
	}
	src, dst, tag, err := store.CopyPage(pageNumber, rightPage)
	if err != nil {
		return branchSplit{}, false, err
	}
	if err := buildReplacement4(src, header, edit, middle, total, dst); err != nil {
		return branchSplit{}, false, err
	}
	if err := store.RestoreDirty(rightPage, tag); err != nil {
		return branchSplit{}, false, err
	}
	if err := keepLeftReplacement4(store, pageNumber, header, edit, middle); err != nil {
		return branchSplit{}, false, err
	}
	work.PageSplit(1)
	rightFirst, err := firstKey4(codec, store, rightPage, header.Level)
	if err != nil {
		return branchSplit{}, false, err
	}
	leftFirst, err := firstKey4(codec, store, pageNumber, header.Level)
	if err != nil {
		return branchSplit{}, false, err
	}
	return branchSplit{rightPage: rightPage, rightFirst: rightFirst, leftFirst: leftFirst, level: header.Level}, true, nil
}

// InsertIfLocalGap4 inserts one leaf cell into the physical gap
// around its key when the gap is fully local to the probed leaf (Rust
// insert_if_local_gap; the family-specialized form of InsertIfLocalGap
// that the writer routes to).
func InsertIfLocalGap4(codec RangeCodec4, store Store, root *uint32, leafCell []byte, retired RetiredPages, r RangeRecord[RangeKey4], reject *LocalReject[RangeRecord[RangeKey4]]) (RetiredPages, LocalGapOutcome, error) {
	gap := rangeProbe4{codec: codec, r: r}
	if err := requireLeaf4(codec, leafCell); err != nil {
		return retired, LocalGapOutcome{}, err
	}
	if *root == 0 {
		pageNumber, err := NewLeaf(codec, store, leafCell)
		if err != nil {
			return retired, LocalGapOutcome{}, err
		}
		*root = pageNumber
		return retired, LocalGapOutcome{Inserted: true, PageNumber: pageNumber}, nil
	}
	key, err := codec.ReadKey(leafCell, 0)
	if err != nil {
		return retired, LocalGapOutcome{}, err
	}
	var leaf PrivateLeaf
	retired, err = privateRangePath4(store, root, key, retired, &leaf)
	if err != nil {
		return retired, LocalGapOutcome{}, err
	}
	if retired.Len() != 0 {
		return retired, LocalGapOutcome{}, corrupt("private B+tree contains a committed page")
	}
	header := leaf.Header
	selector := gapSelector4{codec: codec, key: key, cellLen: len(leafCell), gap: gap}
	index, exists, err := fixedLowerBoundU32(leaf.Page, &header, rangeCellSize4(0), key, true)
	if err != nil {
		return retired, LocalGapOutcome{}, err
	}
	decision, err := selector.selectAt(leaf.Page, header, &leaf.Path, index, exists)
	if err != nil {
		return retired, LocalGapOutcome{}, err
	}
	if !decision.insert {
		built, err := rejection(leaf.Path, leaf.PageNumber, leaf.Header, decision)
		if err != nil {
			return retired, LocalGapOutcome{}, err
		}
		*reject = built
		return retired, LocalGapOutcome{}, nil
	}
	target := LeafTarget{Path: leaf.Path, PageNumber: leaf.PageNumber, Header: leaf.Header, Index: decision.index, Exists: false}
	pageNumber := target.PageNumber
	positioned, fits, err := insertGapTarget(codec, store, root, leafCell, target, key, decision.fits)
	if err != nil {
		return retired, LocalGapOutcome{}, err
	}
	if fits {
		pageNumber = positioned.PageNumber
	}
	return retired, LocalGapOutcome{Inserted: true, PageNumber: pageNumber}, nil
}

// InsertIfCachedInteriorGap4 probes one cached private leaf for a
// fitting interior gap and inserts the cell there (Rust
// insert_if_cached_interior_gap; the family-specialized form of
// InsertIfCachedInteriorGap).
func InsertIfCachedInteriorGap4(codec RangeCodec4, store Store, pageNumber uint32, leafCell []byte, r RangeRecord[RangeKey4]) (CachedInsert, error) {
	gap := rangeProbe4{codec: codec, r: r}
	if err := requireLeaf4(codec, leafCell); err != nil {
		return CachedInsertMiss, err
	}
	key, err := codec.ReadKey(leafCell, 0)
	if err != nil {
		return CachedInsertMiss, err
	}
	level := uint16(0)
	page, err := store.Inspect(pageNumber)
	if err != nil {
		return CachedInsertMiss, err
	}
	header, err := parse(codec, page, store.TargetTxn(), level, true)
	if err != nil {
		return CachedInsertMiss, err
	}
	if format.U64(page[format.HeaderBorn:]) != store.TargetTxn() {
		return CachedInsertMiss, corrupt("leaf locator selected a committed page")
	}
	probeIndex, exists, err := lowerBound(codec, page, &header, key, true)
	if err != nil {
		return CachedInsertMiss, err
	}
	if exists || probeIndex == 0 || probeIndex == int(header.ItemCount) {
		return CachedInsertMiss, nil
	}
	selector := gapSelector4{codec: codec, key: key, cellLen: len(leafCell), gap: gap}
	decision, err := selector.selectAt(page, header, nil, probeIndex, false)
	if err != nil {
		return CachedInsertMiss, err
	}
	if !decision.insert || !decision.fits {
		return CachedInsertMiss, nil
	}
	return CachedInsertInserted, applyLeafEdit(codec, store, pageNumber, &header, Edit{index: decision.index, replace: false, cell: leafCell})
}

// InsertIfEdgeGap4 inserts one leaf cell at a cached private
// tree edge when the local gap is open (Rust insert_if_edge_gap; the
// family-specialized form of InsertIfEdgeGap).
func InsertIfEdgeGap4(codec RangeCodec4, store Store, root *uint32, leafCell []byte, cached *PrivateEdge, edge Edge, knownGap bool, r RangeRecord[RangeKey4]) (EdgeInsert[RangeRecord[RangeKey4]], error) {
	gap := rangeProbe4{codec: codec, r: r}
	if err := requireLeaf4(codec, leafCell); err != nil {
		return EdgeInsert[RangeRecord[RangeKey4]]{}, err
	}
	if *root == 0 {
		return EdgeInsert[RangeRecord[RangeKey4]]{}, corrupt("cached B+tree edge has an empty root")
	}
	if err := verifyCachedEdge(cached, *root, edge); err != nil {
		return EdgeInsert[RangeRecord[RangeKey4]]{}, err
	}
	key, err := codec.ReadKey(leafCell, 0)
	if err != nil {
		return EdgeInsert[RangeRecord[RangeKey4]]{}, err
	}
	level := uint16(0)
	page, err := store.Inspect(cached.position.PageNumber)
	if err != nil {
		return EdgeInsert[RangeRecord[RangeKey4]]{}, err
	}
	header, err := parse(codec, page, store.TargetTxn(), level, true)
	if err != nil {
		return EdgeInsert[RangeRecord[RangeKey4]]{}, err
	}
	if format.U64(page[format.HeaderBorn:]) != store.TargetTxn() {
		return EdgeInsert[RangeRecord[RangeKey4]]{}, corrupt("cached B+tree edge is not private")
	}
	boundary := 0
	if edge == EdgeLast {
		boundary = int(header.ItemCount) - 1
	}
	boundaryKey, err := keyAt(codec, page, &header, boundary)
	if err != nil {
		return EdgeInsert[RangeRecord[RangeKey4]]{}, err
	}
	index := 0
	exists := false
	if edge == EdgeFirst {
		switch {
		case key.Less(boundaryKey):
			index, exists = 0, false
		case key.Equal(boundaryKey):
			index, exists = 0, true
		default:
			return EdgeInsert[RangeRecord[RangeKey4]]{}, corrupt("cached B+tree edge order changed")
		}
	} else {
		switch {
		case boundaryKey.Less(key):
			index, exists = int(header.ItemCount), false
		case key.Equal(boundaryKey):
			index, exists = int(header.ItemCount)-1, true
		default:
			return EdgeInsert[RangeRecord[RangeKey4]]{}, corrupt("cached B+tree edge order changed")
		}
	}
	var decision gapDecision[RangeRecord[RangeKey4]]
	if knownGap {
		if exists {
			return EdgeInsert[RangeRecord[RangeKey4]]{}, corrupt("known B+tree edge gap contains its key")
		}
		decision = gapDecision[RangeRecord[RangeKey4]]{insert: true, index: index, fits: format.SlottedInsertFits(&header, len(leafCell))}
	} else {
		selector := gapSelector4{codec: codec, key: key, cellLen: len(leafCell), gap: gap}
		decision, err = selector.selectAt(page, header, &cached.position.Path, index, exists)
		if err != nil {
			return EdgeInsert[RangeRecord[RangeKey4]]{}, err
		}
	}
	if !decision.insert {
		if err := FlushEdge(codec, store, root, cached); err != nil {
			return EdgeInsert[RangeRecord[RangeKey4]]{}, err
		}
		reject, err := rejection(cached.position.Path, cached.position.PageNumber, header, decision)
		if err != nil {
			return EdgeInsert[RangeRecord[RangeKey4]]{}, err
		}
		return EdgeInsert[RangeRecord[RangeKey4]]{Reject: reject, Rejected: true}, nil
	}
	target := LeafTarget{Path: cached.position.Path, PageNumber: cached.position.PageNumber, Header: header, Index: decision.index, Exists: false}
	if decision.fits {
		var pendingFirst Key
		hasPendingFirst := false
		if target.Index == 0 && target.Path.Depth() != 0 {
			pendingFirst = key
			hasPendingFirst = true
		}
		position, err := applyFittingEdgeInsert(codec, store, target, leafCell)
		if err != nil {
			return EdgeInsert[RangeRecord[RangeKey4]]{}, err
		}
		cached.position = position
		if hasPendingFirst {
			cached.pendingFirst = pendingFirst
			cached.hasPendingFirst = true
		} else {
			cached.hasPendingFirst = false
		}
	} else {
		if err := SplitLeafAtEdge(codec, store, root, &target, leafCell, edge); err != nil {
			return EdgeInsert[RangeRecord[RangeKey4]]{}, err
		}
		cached.hasPendingFirst = false
		position, err := locatePrivatePosition(codec, store, root, key)
		if err != nil {
			return EdgeInsert[RangeRecord[RangeKey4]]{}, err
		}
		cached.position = position
	}
	return EdgeInsert[RangeRecord[RangeKey4]]{Inserted: true, Edge: cached}, nil
}

// InsertRejectedGap4 completes a previously rejected local gap
// insertion after the caller proved the external sides (Rust
// insert_rejected_gap; the family-specialized form of
// InsertRejectedGap).
func InsertRejectedGap4(codec RangeCodec4, store Store, root *uint32, leafCell []byte, rejected LocalReject[RangeRecord[RangeKey4]]) (PrivatePosition, bool, error) {
	if err := requireLeaf4(codec, leafCell); err != nil {
		return PrivatePosition{}, false, err
	}
	key, err := codec.ReadKey(leafCell, 0)
	if err != nil {
		return PrivatePosition{}, false, err
	}
	fits := format.SlottedInsertFits(&rejected.Target.Header, len(leafCell))
	return insertGapTarget(codec, store, root, leafCell, rejected.Target, key, fits)
}

// requireReplacement4 is the concrete limb form of
// RequireReplacement (Rust require_replacement over the fixed key
// type): the cells carry the width-fixed little-endian order key, so
// the limb pairs compare directly and no general tree key is built.
func requireReplacement4(codec RangeCodec4, key Key, cells [][]byte) error {
	if len(cells) < 2 || len(cells) > 3 {
		return invalid("B+tree leaf replacement requires two or three cells")
	}
	var firstHi, firstLo uint64
	var previousHi, previousLo uint64
	for index, cell := range cells {
		if err := requireLeaf4(codec, cell); err != nil {
			return err
		}
		hi, lo, err := codec.ReadKeyLimbs(cell)
		if err != nil {
			return err
		}
		if index == 0 {
			firstHi, firstLo = hi, lo
		} else if previousHi > hi || (previousHi == hi && previousLo >= lo) {
			return invalid("B+tree replacement keys are not increasing")
		}
		previousHi, previousLo = hi, lo
	}
	if firstHi != key.hi || firstLo != key.lo {
		return invalid("B+tree replacement changed its first key")
	}
	return nil
}

// ReplaceLocalPredecessorWith4 replaces the rejected gap's local
// predecessor cell with a 2-3 cell replacement (Rust
// replace_local_predecessor_with; the family-specialized form of
// ReplaceLocalPredecessorWith).
func ReplaceLocalPredecessorWith4(codec RangeCodec4, store Store, root *uint32, rejected *LocalReject[RangeRecord[RangeKey4]], key Key, cells [][]byte) error {
	if err := requireReplacement4(codec, key, cells); err != nil {
		return err
	}
	if !rejected.predecessor.valid {
		return corrupt("B+tree local predecessor is unavailable")
	}
	target := rejected.Target
	target.Index = rejected.predecessorIndex()
	target.Exists = true
	return replaceTarget4(codec, store, root, target, cells)
}

// ReplaceLocalRun4 overwrites one local neighbor cell (or the
// contiguous pair) of a rejected gap with one replacement cell (Rust
// replace_local_run; the family-specialized form of ReplaceLocalRun).
func ReplaceLocalRun4(codec RangeCodec4, store Store, root *uint32, rejected *LocalReject[RangeRecord[RangeKey4]], run LocalRun, replacement []byte) error {
	if err := requireLeaf4(codec, replacement); err != nil {
		return err
	}
	start := 0
	removeCount := 1
	switch run {
	case LocalRunPredecessor:
		if !rejected.predecessor.valid {
			return corrupt("local predecessor is unavailable")
		}
		start = rejected.predecessorIndex()
	case LocalRunSuccessor:
		if !rejected.successor.valid {
			return corrupt("local successor is unavailable")
		}
		start = rejected.successorIndex()
	case LocalRunBoth:
		if !rejected.predecessor.valid {
			return corrupt("local predecessor is unavailable")
		}
		if !rejected.successor.valid {
			return corrupt("local successor is unavailable")
		}
		if rejected.successorIndex() != rejected.predecessorIndex()+1 {
			return corrupt("local B+tree run is not contiguous")
		}
		start = rejected.predecessorIndex()
		removeCount = 2
	}
	target := &rejected.Target
	if start+removeCount > int(target.Header.ItemCount) {
		return corrupt("local B+tree run is outside its leaf")
	}
	replacementKey, err := codec.ReadKey(replacement, 0)
	if err != nil {
		return err
	}
	page, tag, err := store.Update(target.PageNumber)
	if err != nil {
		return err
	}
	oldLen, err := format.SlottedCell(page, &target.Header, start, codec.LeafSize())
	if err != nil {
		return corrupt("slotted-page cell is outside the record area")
	}
	oldLenBytes := len(oldLen)
	if len(replacement) != oldLenBytes {
		return unsupported("local B+tree run replacement changed cell size")
	}
	if start > 0 {
		previous, err := keyAt(codec, page, &target.Header, start-1)
		if err != nil {
			return err
		}
		if !previous.Less(replacementKey) {
			return corrupt("local B+tree replacement is out of order")
		}
	}
	if start+removeCount < int(target.Header.ItemCount) {
		next, err := keyAt(codec, page, &target.Header, start+removeCount)
		if err != nil {
			return err
		}
		if !replacementKey.Less(next) {
			return corrupt("local B+tree replacement is out of order")
		}
	}
	changed, err := format.SlottedReplace(page, &target.Header, start, oldLenBytes, replacement)
	if err != nil {
		return err
	}
	if !changed {
		return corrupt("local B+tree replacement no longer fits")
	}
	header := target.Header
	for i := 1; i < removeCount; i++ {
		cell, err := format.SlottedCell(page, &header, start+1, codec.LeafSize())
		if err != nil {
			return corrupt("slotted-page cell is outside the record area")
		}
		if err := format.SlottedRemove(page, &header, start+1, len(cell)); err != nil {
			return err
		}
		header.ItemCount--
		header.Lower -= 2
		header.Upper += uint16(len(cell))
	}
	if err := store.RestoreDirty(target.PageNumber, tag); err != nil {
		return err
	}
	if start == 0 {
		if err := PropagateFirst(codec, store, root, &target.Path, replacementKey); err != nil {
			return err
		}
	}
	return nil
}

var _ = work.KeyProbe
