// Code generated by genfamilies; DO NOT EDIT.
//
// Family-specialized gap/replace layer (SOW-0027 regression slice
// I-1b): the concrete 4-byte RangeCodec4 probe, selector,
// and tree entries with the codec calls inlined, mirroring Rust's
// monomorphized fixed_tree/gap.rs over RangeCodec<Ipv4Key>/Ipv6Key.
// The single authoritative source is internal/tree/genfamilies; edit
// the generator, not this file.

package tree

import (
	"github.com/firehol/iprange/v4/go/internal/format"
	"github.com/firehol/iprange/v4/go/internal/work"
)

// rangeProbe4 is the concrete RangeCodec4 local-gap probe
// (Rust PrivateGap<RangeCodec<IpvXKey>>): every family operation is a
// direct call on the concrete codec, so one probe never dispatches
// through an interface.
type rangeProbe4 struct {
	codec RangeCodec4
	r     RangeRecord[RangeKey4]
}

func (g rangeProbe4) decode(cell []byte) (RangeRecord[RangeKey4], error) {
	return g.codec.ReadLeaf(cell)
}

// Previous implements the LocalGap probe by value (Rust
// LocalGap::previous): the raw probing cell is returned so the selector
// decodes it once into the reject value.
func (g rangeProbe4) Previous(exact bool, cell []byte) (LocalPrevious, []byte, error) {
	if cell == nil {
		return LocalPreviousAccept, nil, nil
	}
	previous, err := g.decode(cell)
	if err != nil {
		return 0, nil, err
	}
	bridges := false
	if next, ok := g.codec.Next(previous.To); ok {
		bridges = g.codec.Equal(next, g.r.From)
	}
	if exact || !g.codec.Less(previous.To, g.r.From) ||
		(previous.Value == g.r.Value && bridges) {
		return LocalPreviousReject, cell, nil
	}
	return LocalPreviousAccept, nil, nil
}

// Next implements the LocalGap probe by value (Rust LocalGap::next).
func (g rangeProbe4) Next(cell []byte) (LocalNext, []byte, error) {
	if cell == nil {
		return LocalNextAccept, nil, nil
	}
	next, err := g.decode(cell)
	if err != nil {
		return 0, nil, err
	}
	bridges := false
	if boundary, ok := g.codec.Next(g.r.To); ok {
		bridges = g.codec.Equal(boundary, next.From)
	}
	if g.codec.Less(g.r.To, next.From) && (next.Value != g.r.Value || !bridges) {
		return LocalNextAccept, nil, nil
	}
	return LocalNextReject, cell, nil
}

// gapSelector4 is the concrete RangeCodec4 gap selector
// (Rust GapSelector<RangeCodec<IpvXKey>, PrivateGap<...>>).
type gapSelector4 struct {
	codec   RangeCodec4
	key     Key
	cellLen int
	gap     rangeProbe4
}

// selectAt decides the gap at one already-located position (Rust
// GapSelector::select_at).
func (g *gapSelector4) selectAt(page []byte, header Header, path *Path, index int, exists bool) (gapDecision[RangeRecord[RangeKey4]], error) {
	predecessor, predecessorComplete, err := g.probePredecessor(page, header, path, index, exists)
	if err != nil {
		return gapDecision[RangeRecord[RangeKey4]]{}, err
	}
	successor, successorComplete, err := g.probeSuccessor(page, header, path, index, exists)
	if err != nil {
		return gapDecision[RangeRecord[RangeKey4]]{}, err
	}
	if predecessor.valid || successor.valid || !predecessorComplete || !successorComplete {
		return gapDecision[RangeRecord[RangeKey4]]{
			insert:              false,
			index:               index,
			predecessor:         predecessor,
			successor:           successor,
			predecessorComplete: predecessorComplete,
			successorComplete:   successorComplete,
		}, nil
	}
	return gapDecision[RangeRecord[RangeKey4]]{insert: true, index: index, fits: format.SlottedInsertFits(&header, g.cellLen)}, nil
}

func (g *gapSelector4) probePredecessor(page []byte, header Header, path *Path, index int, exists bool) (rejectCell[RangeRecord[RangeKey4]], bool, error) {
	if exists {
		cell, err := g.validLeaf(page, header, index)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		decision, raw, err := g.gap.Previous(true, cell)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		if decision == LocalPreviousAccept {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, corrupt("exact B+tree key was accepted as a gap")
		}
		value, err := g.codec.ReadLeaf(raw)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		return rejectCell[RangeRecord[RangeKey4]]{index: index, value: value, valid: true}, true, nil
	}
	if index > 0 {
		cell, err := g.validLeaf(page, header, index-1)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		decision, raw, err := g.gap.Previous(false, cell)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		if decision == LocalPreviousAccept {
			return rejectCell[RangeRecord[RangeKey4]]{}, true, nil
		}
		value, err := g.codec.ReadLeaf(raw)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		return rejectCell[RangeRecord[RangeKey4]]{index: index - 1, value: value, valid: true}, true, nil
	}
	if allFirst(path) {
		decision, _, err := g.gap.Previous(false, nil)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		if decision == LocalPreviousReject {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, corrupt("absent B+tree predecessor was rejected")
		}
		return rejectCell[RangeRecord[RangeKey4]]{}, true, nil
	}
	return rejectCell[RangeRecord[RangeKey4]]{}, false, nil
}

func (g *gapSelector4) probeSuccessor(page []byte, header Header, path *Path, index int, exists bool) (rejectCell[RangeRecord[RangeKey4]], bool, error) {
	successorIndex := index
	if exists {
		successorIndex++
	}
	if successorIndex < int(header.ItemCount) {
		cell, err := g.validLeaf(page, header, successorIndex)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		decision, raw, err := g.gap.Next(cell)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		if decision == LocalNextAccept {
			return rejectCell[RangeRecord[RangeKey4]]{}, true, nil
		}
		value, err := g.codec.ReadLeaf(raw)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		return rejectCell[RangeRecord[RangeKey4]]{index: successorIndex, value: value, valid: true}, true, nil
	}
	if allLast(path) {
		decision, _, err := g.gap.Next(nil)
		if err != nil {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, err
		}
		if decision == LocalNextReject {
			return rejectCell[RangeRecord[RangeKey4]]{}, false, corrupt("absent B+tree successor was rejected")
		}
		return rejectCell[RangeRecord[RangeKey4]]{}, true, nil
	}
	return rejectCell[RangeRecord[RangeKey4]]{}, false, nil
}

// validLeaf re-verifies one leaf cell through the concrete codec (Rust
// validated_leaf): one SlottedCell read plus one ReadLeaf decode, no
// interface dispatch and no second decode anywhere else on the probe.
func (g gapSelector4) validLeaf(page []byte, header Header, index int) ([]byte, error) {
	cell, err := format.SlottedCell(page, &header, index, g.codec.LeafSize())
	if err != nil {
		return nil, corrupt("slotted-page cell is outside the record area")
	}
	if _, err := g.codec.ReadLeaf(cell); err != nil {
		return nil, err
	}
	return cell, nil
}

// InsertIfLocalGap4 inserts one leaf cell into the physical gap
// around its key when the gap is fully local to the probed leaf (Rust
// insert_if_local_gap; the family-specialized form of InsertIfLocalGap
// that the writer routes to).
func InsertIfLocalGap4(codec RangeCodec4, store Store, root *uint32, leafCell []byte, retired RetiredPages, r RangeRecord[RangeKey4]) (RetiredPages, LocalInsert[RangeRecord[RangeKey4]], error) {
	gap := rangeProbe4{codec: codec, r: r}
	if err := RequireLeaf(codec, leafCell); err != nil {
		return RetiredPages{}, LocalInsert[RangeRecord[RangeKey4]]{}, err
	}
	if *root == 0 {
		pageNumber, err := NewLeaf(codec, store, leafCell)
		if err != nil {
			return RetiredPages{}, LocalInsert[RangeRecord[RangeKey4]]{}, err
		}
		*root = pageNumber
		return retired, LocalInsert[RangeRecord[RangeKey4]]{Inserted: true, PageNumber: pageNumber}, nil
	}
	key, err := codec.ReadKey(leafCell, 0)
	if err != nil {
		return RetiredPages{}, LocalInsert[RangeRecord[RangeKey4]]{}, err
	}
	leaf, retired, err := privatePathSelect(codec, store, root, key, retired)
	if err != nil {
		return RetiredPages{}, LocalInsert[RangeRecord[RangeKey4]]{}, err
	}
	if retired.Len() != 0 {
		return RetiredPages{}, LocalInsert[RangeRecord[RangeKey4]]{}, corrupt("private B+tree contains a committed page")
	}
	header := leaf.Header
	selector := gapSelector4{codec: codec, key: key, cellLen: len(leafCell), gap: gap}
	index, exists, err := lowerBound(codec, leaf.Page, &header, key, true)
	if err != nil {
		return RetiredPages{}, LocalInsert[RangeRecord[RangeKey4]]{}, err
	}
	decision, err := selector.selectAt(leaf.Page, header, &leaf.Path, index, exists)
	if err != nil {
		return RetiredPages{}, LocalInsert[RangeRecord[RangeKey4]]{}, err
	}
	if !decision.insert {
		reject, err := rejection(leaf.Path, leaf.PageNumber, leaf.Header, decision)
		if err != nil {
			return RetiredPages{}, LocalInsert[RangeRecord[RangeKey4]]{}, err
		}
		return retired, LocalInsert[RangeRecord[RangeKey4]]{Reject: reject, Rejected: true}, nil
	}
	target := LeafTarget{Path: leaf.Path, PageNumber: leaf.PageNumber, Header: leaf.Header, Index: decision.index, Exists: false}
	pageNumber := target.PageNumber
	positioned, fits, err := insertGapTarget(codec, store, root, leafCell, target, key, decision.fits)
	if err != nil {
		return RetiredPages{}, LocalInsert[RangeRecord[RangeKey4]]{}, err
	}
	if fits {
		pageNumber = positioned.PageNumber
	}
	return retired, LocalInsert[RangeRecord[RangeKey4]]{Inserted: true, PageNumber: pageNumber}, nil
}

// InsertIfCachedInteriorGap4 probes one cached private leaf for a
// fitting interior gap and inserts the cell there (Rust
// insert_if_cached_interior_gap; the family-specialized form of
// InsertIfCachedInteriorGap).
func InsertIfCachedInteriorGap4(codec RangeCodec4, store Store, pageNumber uint32, leafCell []byte, r RangeRecord[RangeKey4]) (CachedInsert, error) {
	gap := rangeProbe4{codec: codec, r: r}
	if err := RequireLeaf(codec, leafCell); err != nil {
		return CachedInsertMiss, err
	}
	key, err := codec.ReadKey(leafCell, 0)
	if err != nil {
		return CachedInsertMiss, err
	}
	level := uint16(0)
	page, err := store.Inspect(pageNumber)
	if err != nil {
		return CachedInsertMiss, err
	}
	header, err := parse(codec, page, store.TargetTxn(), level, true)
	if err != nil {
		return CachedInsertMiss, err
	}
	if format.U64(page[format.HeaderBorn:]) != store.TargetTxn() {
		return CachedInsertMiss, corrupt("leaf locator selected a committed page")
	}
	probeIndex, exists, err := lowerBound(codec, page, &header, key, true)
	if err != nil {
		return CachedInsertMiss, err
	}
	if exists || probeIndex == 0 || probeIndex == int(header.ItemCount) {
		return CachedInsertMiss, nil
	}
	selector := gapSelector4{codec: codec, key: key, cellLen: len(leafCell), gap: gap}
	decision, err := selector.selectAt(page, header, nil, probeIndex, false)
	if err != nil {
		return CachedInsertMiss, err
	}
	if !decision.insert || !decision.fits {
		return CachedInsertMiss, nil
	}
	return CachedInsertInserted, applyLeafEdit(codec, store, pageNumber, &header, Edit{index: decision.index, replace: false, cell: leafCell})
}

// InsertIfEdgeGap4 inserts one leaf cell at a cached private
// tree edge when the local gap is open (Rust insert_if_edge_gap; the
// family-specialized form of InsertIfEdgeGap).
func InsertIfEdgeGap4(codec RangeCodec4, store Store, root *uint32, leafCell []byte, cached *PrivateEdge, edge Edge, knownGap bool, r RangeRecord[RangeKey4]) (EdgeInsert[RangeRecord[RangeKey4]], error) {
	gap := rangeProbe4{codec: codec, r: r}
	if err := RequireLeaf(codec, leafCell); err != nil {
		return EdgeInsert[RangeRecord[RangeKey4]]{}, err
	}
	if *root == 0 {
		return EdgeInsert[RangeRecord[RangeKey4]]{}, corrupt("cached B+tree edge has an empty root")
	}
	if err := verifyCachedEdge(cached, *root, edge); err != nil {
		return EdgeInsert[RangeRecord[RangeKey4]]{}, err
	}
	key, err := codec.ReadKey(leafCell, 0)
	if err != nil {
		return EdgeInsert[RangeRecord[RangeKey4]]{}, err
	}
	level := uint16(0)
	page, err := store.Inspect(cached.position.PageNumber)
	if err != nil {
		return EdgeInsert[RangeRecord[RangeKey4]]{}, err
	}
	header, err := parse(codec, page, store.TargetTxn(), level, true)
	if err != nil {
		return EdgeInsert[RangeRecord[RangeKey4]]{}, err
	}
	if format.U64(page[format.HeaderBorn:]) != store.TargetTxn() {
		return EdgeInsert[RangeRecord[RangeKey4]]{}, corrupt("cached B+tree edge is not private")
	}
	boundary := 0
	if edge == EdgeLast {
		boundary = int(header.ItemCount) - 1
	}
	boundaryKey, err := keyAt(codec, page, &header, boundary)
	if err != nil {
		return EdgeInsert[RangeRecord[RangeKey4]]{}, err
	}
	index := 0
	exists := false
	if edge == EdgeFirst {
		switch {
		case key.Less(boundaryKey):
			index, exists = 0, false
		case key.Equal(boundaryKey):
			index, exists = 0, true
		default:
			return EdgeInsert[RangeRecord[RangeKey4]]{}, corrupt("cached B+tree edge order changed")
		}
	} else {
		switch {
		case boundaryKey.Less(key):
			index, exists = int(header.ItemCount), false
		case key.Equal(boundaryKey):
			index, exists = int(header.ItemCount)-1, true
		default:
			return EdgeInsert[RangeRecord[RangeKey4]]{}, corrupt("cached B+tree edge order changed")
		}
	}
	var decision gapDecision[RangeRecord[RangeKey4]]
	if knownGap {
		if exists {
			return EdgeInsert[RangeRecord[RangeKey4]]{}, corrupt("known B+tree edge gap contains its key")
		}
		decision = gapDecision[RangeRecord[RangeKey4]]{insert: true, index: index, fits: format.SlottedInsertFits(&header, len(leafCell))}
	} else {
		selector := gapSelector4{codec: codec, key: key, cellLen: len(leafCell), gap: gap}
		decision, err = selector.selectAt(page, header, &cached.position.Path, index, exists)
		if err != nil {
			return EdgeInsert[RangeRecord[RangeKey4]]{}, err
		}
	}
	if !decision.insert {
		if err := FlushEdge(codec, store, root, cached); err != nil {
			return EdgeInsert[RangeRecord[RangeKey4]]{}, err
		}
		reject, err := rejection(cached.position.Path, cached.position.PageNumber, header, decision)
		if err != nil {
			return EdgeInsert[RangeRecord[RangeKey4]]{}, err
		}
		return EdgeInsert[RangeRecord[RangeKey4]]{Reject: reject, Rejected: true}, nil
	}
	target := LeafTarget{Path: cached.position.Path, PageNumber: cached.position.PageNumber, Header: header, Index: decision.index, Exists: false}
	if decision.fits {
		var pendingFirst Key
		hasPendingFirst := false
		if target.Index == 0 && target.Path.Depth() != 0 {
			pendingFirst = key
			hasPendingFirst = true
		}
		position, err := applyFittingEdgeInsert(codec, store, target, leafCell)
		if err != nil {
			return EdgeInsert[RangeRecord[RangeKey4]]{}, err
		}
		cached.position = position
		if hasPendingFirst {
			cached.pendingFirst = pendingFirst
			cached.hasPendingFirst = true
		} else {
			cached.hasPendingFirst = false
		}
	} else {
		if err := SplitLeafAtEdge(codec, store, root, &target, leafCell, edge); err != nil {
			return EdgeInsert[RangeRecord[RangeKey4]]{}, err
		}
		cached.hasPendingFirst = false
		position, err := locatePrivatePosition(codec, store, root, key)
		if err != nil {
			return EdgeInsert[RangeRecord[RangeKey4]]{}, err
		}
		cached.position = position
	}
	return EdgeInsert[RangeRecord[RangeKey4]]{Inserted: true, Edge: cached}, nil
}

// InsertRejectedGap4 completes a previously rejected local gap
// insertion after the caller proved the external sides (Rust
// insert_rejected_gap; the family-specialized form of
// InsertRejectedGap).
func InsertRejectedGap4(codec RangeCodec4, store Store, root *uint32, leafCell []byte, rejected LocalReject[RangeRecord[RangeKey4]]) (PrivatePosition, bool, error) {
	if err := RequireLeaf(codec, leafCell); err != nil {
		return PrivatePosition{}, false, err
	}
	key, err := codec.ReadKey(leafCell, 0)
	if err != nil {
		return PrivatePosition{}, false, err
	}
	fits := format.SlottedInsertFits(&rejected.Target.Header, len(leafCell))
	return insertGapTarget(codec, store, root, leafCell, rejected.Target, key, fits)
}

// requireReplacement4 is the concrete limb form of
// RequireReplacement (Rust require_replacement over the fixed key
// type): the cells carry the width-fixed little-endian order key, so
// the limb pairs compare directly and no general tree key is built.
func requireReplacement4(codec RangeCodec4, key Key, cells [][]byte) error {
	if len(cells) < 2 || len(cells) > 3 {
		return invalid("B+tree leaf replacement requires two or three cells")
	}
	var firstHi, firstLo uint64
	var previousHi, previousLo uint64
	for index, cell := range cells {
		if err := RequireLeaf(codec, cell); err != nil {
			return err
		}
		hi, lo, err := codec.ReadKeyLimbs(cell)
		if err != nil {
			return err
		}
		if index == 0 {
			firstHi, firstLo = hi, lo
		} else if previousHi > hi || (previousHi == hi && previousLo >= lo) {
			return invalid("B+tree replacement keys are not increasing")
		}
		previousHi, previousLo = hi, lo
	}
	if firstHi != key.hi || firstLo != key.lo {
		return invalid("B+tree replacement changed its first key")
	}
	return nil
}

// ReplaceLocalPredecessorWith4 replaces the rejected gap's local
// predecessor cell with a 2-3 cell replacement (Rust
// replace_local_predecessor_with; the family-specialized form of
// ReplaceLocalPredecessorWith).
func ReplaceLocalPredecessorWith4(codec RangeCodec4, store Store, root *uint32, rejected LocalReject[RangeRecord[RangeKey4]], key Key, cells [][]byte) error {
	if err := requireReplacement4(codec, key, cells); err != nil {
		return err
	}
	if !rejected.predecessor.valid {
		return corrupt("B+tree local predecessor is unavailable")
	}
	target := rejected.Target
	target.Index = rejected.predecessorIndex()
	target.Exists = true
	return replaceTarget(codec, store, root, target, cells)
}

// ReplaceLocalRun4 overwrites one local neighbor cell (or the
// contiguous pair) of a rejected gap with one replacement cell (Rust
// replace_local_run; the family-specialized form of ReplaceLocalRun).
func ReplaceLocalRun4(codec RangeCodec4, store Store, root *uint32, rejected LocalReject[RangeRecord[RangeKey4]], run LocalRun, replacement []byte) error {
	if err := RequireLeaf(codec, replacement); err != nil {
		return err
	}
	start := 0
	removeCount := 1
	switch run {
	case LocalRunPredecessor:
		if !rejected.predecessor.valid {
			return corrupt("local predecessor is unavailable")
		}
		start = rejected.predecessorIndex()
	case LocalRunSuccessor:
		if !rejected.successor.valid {
			return corrupt("local successor is unavailable")
		}
		start = rejected.successorIndex()
	case LocalRunBoth:
		if !rejected.predecessor.valid {
			return corrupt("local predecessor is unavailable")
		}
		if !rejected.successor.valid {
			return corrupt("local successor is unavailable")
		}
		if rejected.successorIndex() != rejected.predecessorIndex()+1 {
			return corrupt("local B+tree run is not contiguous")
		}
		start = rejected.predecessorIndex()
		removeCount = 2
	}
	target := &rejected.Target
	if start+removeCount > int(target.Header.ItemCount) {
		return corrupt("local B+tree run is outside its leaf")
	}
	replacementKey, err := codec.ReadKey(replacement, 0)
	if err != nil {
		return err
	}
	page, tag, err := store.Update(target.PageNumber)
	if err != nil {
		return err
	}
	oldLen, err := format.SlottedCell(page, &target.Header, start, codec.LeafSize())
	if err != nil {
		return corrupt("slotted-page cell is outside the record area")
	}
	oldLenBytes := len(oldLen)
	if len(replacement) != oldLenBytes {
		return unsupported("local B+tree run replacement changed cell size")
	}
	if start > 0 {
		previous, err := keyAt(codec, page, &target.Header, start-1)
		if err != nil {
			return err
		}
		if !previous.Less(replacementKey) {
			return corrupt("local B+tree replacement is out of order")
		}
	}
	if start+removeCount < int(target.Header.ItemCount) {
		next, err := keyAt(codec, page, &target.Header, start+removeCount)
		if err != nil {
			return err
		}
		if !replacementKey.Less(next) {
			return corrupt("local B+tree replacement is out of order")
		}
	}
	changed, err := format.SlottedReplace(page, &target.Header, start, oldLenBytes, replacement)
	if err != nil {
		return err
	}
	if !changed {
		return corrupt("local B+tree replacement no longer fits")
	}
	header := target.Header
	for i := 1; i < removeCount; i++ {
		cell, err := format.SlottedCell(page, &header, start+1, codec.LeafSize())
		if err != nil {
			return corrupt("slotted-page cell is outside the record area")
		}
		if err := format.SlottedRemove(page, &header, start+1, len(cell)); err != nil {
			return err
		}
		header.ItemCount--
		header.Lower -= 2
		header.Upper += uint16(len(cell))
	}
	if err := store.RestoreDirty(target.PageNumber, tag); err != nil {
		return err
	}
	if start == 0 {
		if err := PropagateFirst(codec, store, root, &target.Path, replacementKey); err != nil {
			return err
		}
	}
	return nil
}

var _ = work.KeyProbe
