// Boundary corpus: the routine static gate check (SOW-0025 decision
// 2026-08-19, reinforced by the user decision of 2026-08-21 that
// permanently retires the heavy mutation battery). One representative
// form per launder family and per view-holder package; every fail form
// below must make the gate reject the tree, every benign form must
// stay clean. The heavy battery previously lived in battery.go and
// battery_page.go (718+ forms); it was removed by user decision - the
// enforced guarantees are the code-isolation architecture (view-holder
// whitelist) plus this static corpus and the full-module scans; the
// mutation battery is never run again.

package main

type batteryOp struct {
	kind    string // "create" | "append" | "ins" | "inject"
	path    string
	content string
}

type batteryCase struct {
	name       string
	desc       string
	expectFail bool
	// expectRule, when set, is a substring that must appear in a gate
	// violation; an unrelated type-check failure cannot satisfy the case.
	expectRule string
	// allowTypeCheck marks deliberately invalid-Go or binary-only
	// fail-closed shapes whose rejection is itself the contract.
	allowTypeCheck bool
	ops            []batteryOp
}

var boundaryCorpus = []batteryCase{
	batteryCase{name: "1: direct io.ReadAll call", desc: "direct io.ReadAll call", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "gatemut_readall/mut.go", content: "package gatemut_readall\n\nimport (\n\t\"io\"\n\t\"os\"\n)\n\nvar file *os.File\n\nfunc use() { _, _ = io.ReadAll(file) }"}}},
	batteryCase{name: "2: io.ReadAll function alias", desc: "io.ReadAll function alias", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "gatemut_alias/mut.go", content: "package gatemut_alias\n\nimport (\n\t\"io\"\n\t\"os\"\n)\n\nvar file *os.File\n\nvar rd = io.ReadAll\n\nfunc use() { _, _ = rd(file) }"}}},
	batteryCase{name: "3: os.File.Read method value", desc: "os.File.Read method value", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "gatemut_methodval/mut.go", content: "package gatemut_methodval\n\nimport \"os\"\n\nvar file *os.File\n\nvar m = file.Read\n\nfunc use() { var b []byte; _, _ = m(b) }"}}},
	batteryCase{name: "4: os.File.Seek call", desc: "os.File.Seek call", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "gatemut_seek/mut.go", content: "package gatemut_seek\n\nimport \"os\"\n\nvar file *os.File\n\nfunc use() { _, _ = file.Seek(0, 0) }"}}},
	batteryCase{name: "5: os.ReadFile in a new package directory", desc: "os.ReadFile in a new package directory", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "gatemut_newdir/mut.go", content: "package gatemut_newdir\n\nimport \"os\"\n\nfunc read(p string) ([]byte, error) { return os.ReadFile(p) }"}}},
	batteryCase{name: "6: unix.Readv descriptor read in the mapping owner", desc: "unix.Readv descriptor read in the mapping owner", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/mapping/gatemut_readv.go", content: "package mapping\n\nimport \"golang.org/x/sys/unix\"\n\nfunc readv(fd int, b [][]byte) (int, error) { return unix.Readv(fd, b) }"}}},
	batteryCase{name: "7: bufio.NewReader(file).ReadByte", desc: "bufio.NewReader(file).ReadByte", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "gatemut_bufio/mut.go", content: "package gatemut_bufio\n\nimport (\n\t\"bufio\"\n\t\"os\"\n)\n\nvar file *os.File\n\nfunc use() (byte, error) { return bufio.NewReader(file).ReadByte() }"}}},
	batteryCase{name: "8: dot-imported os.ReadFile", desc: "dot-imported os.ReadFile", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "gatemut_dotimport/mut.go", content: "package gatemut_dotimport\n\nimport . \"os\"\n\nfunc read(p string) ([]byte, error) { return ReadFile(p) }"}}},
	batteryCase{name: "12: fmt.Fscan over a file", desc: "fmt.Fscan over a file", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "gatemut_fscan/mut.go", content: "package gatemut_fscan\n\nimport (\n\t\"fmt\"\n\t\"os\"\n)\n\nvar f *os.File\n\nfunc use(x any) (int, error) { return fmt.Fscan(f, x) }"}}},
	batteryCase{name: "14: reflection-invoked Read", desc: "reflection-invoked Read", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "gatemut_reflect/mut.go", content: "package gatemut_reflect\n\nimport (\n\t\"os\"\n\t\"reflect\"\n)\n\nvar f *os.File\n\nfunc use() { _ = reflect.ValueOf(f).MethodByName(\"Read\").Call(nil) }"}}},
	batteryCase{name: "15: raw unix.Syscall(SYS_READ) in the mapping owner", desc: "raw unix.Syscall(SYS_READ) in the mapping owner", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/mapping/gatemut_rawsys.go", content: "package mapping\n\nimport \"golang.org/x/sys/unix\"\n\nfunc rawRead(fd int) (int, error) {\n\tn, _, e := unix.Syscall(unix.SYS_READ, uintptr(fd), 0, 0)\n\treturn int(n), e\n}"}}},
	batteryCase{name: "16: unix.CopyFileRange in the mapping owner", desc: "unix.CopyFileRange in the mapping owner", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/mapping/gatemut_cfr.go", content: "package mapping\n\nimport \"golang.org/x/sys/unix\"\n\nfunc copyRange(a, b, n int) (int, error) {\n\treturn unix.CopyFileRange(a, nil, b, nil, n, 0)\n}"}}},
	batteryCase{name: "19: encoding/json decoder over a file", desc: "encoding/json decoder over a file", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "gatemut_decoder/mut.go", content: "package gatemut_decoder\n\nimport (\n\t\"encoding/json\"\n\t\"os\"\n)\n\nvar f *os.File\n\nfunc use() { var x any; _ = json.NewDecoder(f).Decode(&x) }"}}},
	batteryCase{name: "20: os.File.WriteString", desc: "os.File.WriteString", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "gatemut_writestr/mut.go", content: "package gatemut_writestr\n\nimport \"os\"\n\nvar f *os.File\n\nfunc use() { _, _ = f.WriteString(\"payload\") }"}}},
	batteryCase{name: "25: log package writing to a file", desc: "log package writing to a file", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "gatemut_logw/mut.go", content: "package gatemut_logw\n\nimport (\n\t\"log\"\n\t\"os\"\n)\n\nvar f *os.File\n\nfunc use() { log.New(f, \"\", 0).Println(\"payload\") }"}}},
	batteryCase{name: "26: flate.NewWriter over a file", desc: "flate.NewWriter over a file", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "gatemut_flatew/mut.go", content: "package gatemut_flatew\n\nimport (\n\t\"compress/flate\"\n\t\"os\"\n)\n\nvar f *os.File\n\nfunc use() { w, _ := flate.NewWriter(f, 6); w.Close() }"}}},
	batteryCase{name: "38: os.StartProcess with the artifact file attached", desc: "os.StartProcess with the artifact file attached", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/mapping/gatemut_startproc.go", content: "package mapping\n\nimport \"os\"\n\nfunc transferChild(path string, file *os.File) (*os.Process, error) {\n\treturn os.StartProcess(\"/bin/cat\", []string{\"cat\", path}, &os.ProcAttr{Files: []*os.File{file, file, file}})\n}"}}},
	batteryCase{name: "P1: copy of a full mapped page into an owned [4096]byte", desc: "copy(page, [4096]byte) in the mapping owner", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/mapping/gatemut_pagecopy.go", content: "package mapping\n\nfunc pageCopyProbe(m *Mapping) ([4096]byte, error) {\n\tpage, err := m.Page(0)\n\tif err != nil {\n\t\treturn [4096]byte{}, err\n\t}\n\tvar out [4096]byte\n\tcopy(out[:], page)\n\treturn out, nil\n}"}}},
	batteryCase{name: "P2: append of a full mapped page into an owned buffer", desc: "append(owned, page...) in the reader core", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_pageappend.go", content: "package reader\n\nimport \"github.com/firehol/iprange/v4/go/internal/mapping\"\n\nfunc pageAppendProbe(m *mapping.Mapping) ([]byte, error) {\n\tpage, err := m.Page(0)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\tout := make([]byte, 0, 8192)\n\tout = append(out, page...)\n\treturn out, nil\n}"}}},
	batteryCase{name: "P4: array conversion of a full mapped page", desc: "[4096]byte(page) in the reader core", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_pagearr.go", content: "package reader\n\nimport \"github.com/firehol/iprange/v4/go/internal/mapping\"\n\nfunc pageArrayProbe(m *mapping.Mapping) ([4096]byte, error) {\n\tpage, err := m.Page(0)\n\tif err != nil {\n\t\treturn [4096]byte{}, err\n\t}\n\treturn [4096]byte(page), nil\n}"}}},
	batteryCase{name: "P6: benign bounded record copy below a complete page", desc: "bounded record copy below a complete page stays legal", expectFail: false, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_boundedcopy.go", content: "package reader\n\nimport \"github.com/firehol/iprange/v4/go/internal/mapping\"\n\nfunc boundedCopyProbe(m *mapping.Mapping) ([]byte, error) {\n\tpage, err := m.Page(0)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\trec := page[48:112]\n\tout := make([]byte, 64)\n\tcopy(out, rec)\n\treturn out, nil\n}"}}},
	batteryCase{name: "P7: benign bounded metadata-chunk append stays legal", desc: "append of a decoded metadata chunk keeps its 4048 bound", expectFail: false, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_chunkappend.go", content: "package reader\n\nimport \"github.com/firehol/iprange/v4/go/internal/format\"\n\nfunc chunkAppendProbe(page []byte) []byte {\n\tchunk, err := format.DecodeMetadataChunk(page)\n\tif err != nil {\n\t\treturn nil\n\t}\n\tout := make([]byte, 0, 8192)\n\tout = append(out, chunk.Data...)\n\treturn out\n}"}}},
	batteryCase{name: "P8: full mapped page through a function variable", desc: "stdlib func bound into a same-package var and called with a page", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_fnvarpage.go", content: "package reader\n\nimport \"bytes\"\n\nvar clonePage = bytes.Clone\n\nfunc fnVarPageProbe(r *ImmutableReader, pgno uint32) ([]byte, error) {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\treturn clonePage(page), nil\n}"}}},
	batteryCase{name: "P9: benign function variable without a page argument", desc: "func var called with an owned buffer stays legal", expectFail: false, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_fnvarplain.go", content: "package reader\n\nimport \"bytes\"\n\nvar clonePlain = bytes.Clone\n\nfunc fnVarPlainProbe() []byte {\n\treturn clonePlain(make([]byte, 64))\n}"}}},
	batteryCase{name: "P10: benign same-package call carries a mapped page", desc: "direct same-package func call with a page view stays legal (body scanned)", expectFail: false, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_pkgfnpage.go", content: "package reader\n\nfunc pagePassThrough(page []byte) []byte { return page }\n\nfunc pkgFnPageProbe(r *ImmutableReader, pgno uint32) ([]byte, error) {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\treturn pagePassThrough(page), nil\n}"}}},
	batteryCase{name: "P11: full page copied inside a defer closure", desc: "defer func(){ copy(out[:], page) }() in the reader core", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_deferpage.go", content: "package reader\n\nfunc deferPageProbe(r *ImmutableReader, pgno uint32) ([4096]byte, error) {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn [4096]byte{}, err\n\t}\n\tvar out [4096]byte\n\tdefer func() { copy(out[:], page) }()\n\treturn out, nil\n}"}}},
	batteryCase{name: "P13: full page copied inside a go closure", desc: "go func(){ copy(out[:], page) }() in the reader core", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_gopage.go", content: "package reader\n\nfunc goPageProbe(r *ImmutableReader, pgno uint32) [4096]byte {\n\tpage, perr := r.page(pgno)\n\tif perr != nil {\n\t\treturn [4096]byte{}\n\t}\n\tvar out [4096]byte\n\tgo func() { copy(out[:], page) }()\n\treturn out\n}"}}},
	batteryCase{name: "P14: benign bounded copy inside a defer closure", desc: "defer func(){ copy(out, page[48:112]) }() stays legal", expectFail: false, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_deferok.go", content: "package reader\n\nfunc deferOkProbe(r *ImmutableReader, pgno uint32) []byte {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn nil\n\t}\n\trec := page[48:112]\n\tout := make([]byte, 64)\n\tdefer func() { copy(out, rec) }()\n\treturn out\n}"}}},
	batteryCase{name: "P16: full page through a func-literal variable", desc: "var f = func(p){ copy(out,p) }; f(page) in the reader core", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_fnlitvar.go", content: "package reader\n\nvar cloneLit = func(page []byte) []byte {\n\tout := make([]byte, len(page))\n\tcopy(out, page)\n\treturn out\n}\n\nfunc fnLitVarProbe(r *ImmutableReader, pgno uint32) ([]byte, error) {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\treturn cloneLit(page), nil\n}"}}},
	batteryCase{name: "P24: append through a same-package pass-through helper", desc: "append(owned, helper(page)...) must not lose the page taint", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_helperappend.go", content: "package reader\n\nfunc pagePassThrough24(page []byte) []byte { return page }\n\nfunc helperAppendProbe(r *ImmutableReader, pgno uint32) ([]byte, error) {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\treturn append([]byte{}, pagePassThrough24(page)...), nil\n}"}}},
	batteryCase{name: "P33: named string conversion of a full page", desc: "type S string; S(page) must be rejected", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_namedstrconv.go", content: "package reader\n\ntype pageStr33 string\n\nfunc namedStrProbe(r *ImmutableReader, pgno uint32) (pageStr33, error) {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn \"\", err\n\t}\n\treturn pageStr33(page), nil\n}"}}},
	batteryCase{name: "P35: bounded View(0, 64) copy stays legal", desc: "copy(out, m.View(0, 64)) must not be treated as a full page", expectFail: false, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_boundedview.go", content: "package reader\n\nimport \"github.com/firehol/iprange/v4/go/internal/mapping\"\n\nfunc boundedViewProbe(m *mapping.Mapping) ([]byte, error) {\n\tv, err := m.View(0, 64)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\tout := make([]byte, 64)\n\tcopy(out, v)\n\treturn out, nil\n}"}}},
	batteryCase{name: "P36: bounded slice through a local closure stays legal", desc: "id(page[48:112]) appended stays below a complete page", expectFail: false, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_closurebounded.go", content: "package reader\n\nfunc closureBoundedProbe(r *ImmutableReader, pgno uint32) ([]byte, error) {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\tid := func(p []byte) []byte { return p }\n\treturn append([]byte{}, id(page[48:112])...), nil\n}"}}},
	batteryCase{name: "P42: void unknown callback receiving a full page", desc: "var fn func([]byte); fn(page) with an unproven void callee must be rejected", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_voidcallback.go", content: "package reader\n\nfunc voidCallbackProbe(r *ImmutableReader, pgno uint32) error {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn err\n\t}\n\tvar fn func([]byte)\n\tfn(page)\n\treturn nil\n}"}}},
	batteryCase{name: "P47: interface boxing conversion keeps page taint", desc: "x := any(page); append(owned, x.([]byte)...) must be rejected", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_anyconv.go", content: "package reader\n\nfunc anyConvProbe(r *ImmutableReader, pgno uint32) ([]byte, error) {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\tx := any(page)\n\treturn append([]byte{}, x.([]byte)...), nil\n}"}}},
	batteryCase{name: "P49: channel round trip keeps page taint", desc: "ch <- page; p := <-ch; append(owned, p...) must be rejected", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_chan.go", content: "package reader\n\nfunc chanProbe(r *ImmutableReader, pgno uint32) ([]byte, error) {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\tch := make(chan []byte)\n\tch <- page\n\tp := <-ch\n\treturn append([]byte{}, p...), nil\n}"}}},
	batteryCase{name: "P55: named result with a bounded view stays legal", desc: "func pass(p []byte) (out []byte) { out = p[48:112]; return } appended stays legal", expectFail: false, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_namedbounded.go", content: "package reader\n\nfunc passB55(p []byte) (out []byte) {\n\tout = p[48:112]\n\treturn\n}\n\nfunc namedBoundedProbe(r *ImmutableReader, pgno uint32) ([]byte, error) {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\treturn append([]byte{}, passB55(page)...), nil\n}"}}},
	batteryCase{name: "P74: string conversion of a page view with an unknown bound", desc: "string(page[0:n]) with runtime n up to page size must be rejected", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_stringunk.go", content: "package reader\n\nfunc stringUnknownProbe74(r *ImmutableReader, pgno uint32, n int) (string, error) {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn \"\", err\n\t}\n\tv := page[0:n]\n\treturn string(v), nil\n}"}}},
	batteryCase{name: "P75: reflect byte extraction over a mapped view", desc: "reflect.ValueOf(page).Bytes() hands out the underlying mapped bytes and must be rejected", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_reflect.go", content: "package reader\n\nimport \"reflect\"\n\nfunc reflectProbe75(r *ImmutableReader, pgno uint32) ([]byte, error) {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\tb := reflect.ValueOf(page).Bytes()\n\treturn append([]byte{}, b...), nil\n}"}}},
	batteryCase{name: "P62: string conversion of a definite full-page view", desc: "string(page[0:4096]) copies a complete mapped page and must be rejected", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_stringfull.go", content: "package reader\n\nfunc stringFullProbe(r *ImmutableReader, pgno uint32) error {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn err\n\t}\n\t_ = string(page[0:4096])\n\treturn nil\n}"}}},
	batteryCase{name: "P63: append into a multi-page mapped view", desc: "append(page[0:8192:8192], 1) reallocates the two-page span into owned memory and must be rejected", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_oversizeddest.go", content: "package reader\n\nfunc oversizedDestProbe(r *ImmutableReader, pgno uint32) ([]byte, error) {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\treturn append(page[0:8192:8192], 1), nil\n}"}}},
	batteryCase{name: "P65: unsafe import anywhere in the module", desc: "import \"unsafe\" in the mapping owner must be rejected (unsafe.Slice over a mapped descriptor escapes the type layer)", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/mapping/gatemut_unsafe.go", content: "package mapping\n\nimport \"unsafe\"\n\nvar _ = unsafe.Pointer(nil)"}}},
	batteryCase{name: "P85: fmt variadic spread of a concrete page collection", desc: "args := []any{page}; fmt.Sprintf(\"%s\", args...) copies the full mapped view into an owned string and must be rejected", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_r9_3.go", content: "package reader\n\nimport \"fmt\"\n\nfunc fmtSpreadProbe85(r *ImmutableReader, pgno uint32) (string, error) {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn \"\", err\n\t}\n\targs := []any{page}\n\treturn fmt.Sprintf(\"%s\", args...), nil\n}"}}},
	batteryCase{name: "P111: complete-page copy through the reader exemption must still be rejected", desc: "io.ReadFull(bytes.NewReader(page), out) copies the mapped page into an owned buffer despite the reader-arg exemption and must be rejected", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_r10_13.go", content: "package reader\n\nimport (\n\t\"bytes\"\n\t\"io\"\n\n\t\"github.com/firehol/iprange/v4/go/internal/format\"\n)\n\nfunc gateProbeR113(r *ImmutableReader, pgno uint32) error {\n\tpage, err := r.page(pgno)\n\tif err != nil {\n\t\treturn err\n\t}\n\tout := make([]byte, format.PageSize)\n\t_, err = io.ReadFull(bytes.NewReader(page), out)\n\treturn err\n}"}}},
	batteryCase{name: "P137: store CopyPage callback copying between mapped pages stays benign", desc: "CopyPage(src, dst, func(src, output []byte) { copy(output, src) }) with the callback seeded as a mapping alias is the module's COW page-copy shape and must pass", expectFail: false, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_cowcb.go", content: "package reader\n\nimport \"github.com/firehol/iprange/v4/go/internal/tree\"\n\ntype cowStoreImpl137 struct{ r *ImmutableReader }\n\nfunc (s cowStoreImpl137) TargetTxn() uint64 { return 0 }\nfunc (s cowStoreImpl137) PageLimit() uint64 { return 0 }\nfunc (s cowStoreImpl137) Inspect(uint32, func([]byte) error) error { return nil }\nfunc (s cowStoreImpl137) Allocate() (uint32, error) { return 0, nil }\nfunc (s cowStoreImpl137) Update(uint32, func([]byte) error) error { return nil }\nfunc (s cowStoreImpl137) DiscardPrivate(uint32) error { return nil }\n\nfunc (s cowStoreImpl137) CopyPage(source, destination uint32, fn func(src, output []byte) error) error {\n\tsrc, err := s.r.page(source)\n\tif err != nil {\n\t\treturn err\n\t}\n\tdst, err := s.r.page(destination)\n\tif err != nil {\n\t\treturn err\n\t}\n\treturn fn(src, dst)\n}\n\nfunc cowCbProbe137(s tree.Store, src, dst uint32) error {\n\treturn s.CopyPage(src, dst, func(src, output []byte) error {\n\t\tcopy(output, src)\n\t\treturn nil\n\t})\n}\n"}}},
	batteryCase{name: "P138: store CopyPage callback laundering a mapped page into an owned buffer fails closed", desc: "the callback appending a seeded mapped src into a package-level owned buffer must be rejected at the append site", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_cowcb_bad.go", content: "package reader\n\nimport \"github.com/firehol/iprange/v4/go/internal/tree\"\n\ntype cowStoreBad138 struct{ r *ImmutableReader }\n\nfunc (s cowStoreBad138) TargetTxn() uint64 { return 0 }\nfunc (s cowStoreBad138) PageLimit() uint64 { return 0 }\nfunc (s cowStoreBad138) Inspect(uint32, func([]byte) error) error { return nil }\nfunc (s cowStoreBad138) Allocate() (uint32, error) { return 0, nil }\nfunc (s cowStoreBad138) Update(uint32, func([]byte) error) error { return nil }\nfunc (s cowStoreBad138) DiscardPrivate(uint32) error { return nil }\n\nfunc (s cowStoreBad138) CopyPage(source, destination uint32, fn func(src, output []byte) error) error {\n\tsrc, err := s.r.page(source)\n\tif err != nil {\n\t\treturn err\n\t}\n\tdst, err := s.r.page(destination)\n\tif err != nil {\n\t\treturn err\n\t}\n\treturn fn(src, dst)\n}\n\nvar sinkBuf138 []byte\n\nfunc cowCbBadProbe138(s tree.Store, src, dst uint32) error {\n\treturn s.CopyPage(src, dst, func(src, output []byte) error {\n\t\tsinkBuf138 = append(sinkBuf138, src...)\n\t\treturn nil\n\t})\n}\n"}}},
	batteryCase{name: "P243: store callback invocation with an owned buffer in a dishonest store implementation fails closed", desc: "CopyPage(src, dst, fn) whose implementation calls fn(s.buf, s.buf) with OWNED buffers violates the store contract: the dispatch-site callback seeding treats the literal params as mapping aliases, so a copy of a real mapped page into the callback's output would launder complete pages into owned memory; the implementation-site check must reject the invocation", expectFail: true, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_liar.go", content: "package reader\n\nimport \"github.com/firehol/iprange/v4/go/internal/tree\"\n\ntype liarStore243 struct{ buf []byte }\n\nfunc (s liarStore243) TargetTxn() uint64 { return 0 }\nfunc (s liarStore243) PageLimit() uint64 { return 0 }\nfunc (s liarStore243) Inspect(uint32, func([]byte) error) error { return nil }\nfunc (s liarStore243) Allocate() (uint32, error) { return 0, nil }\nfunc (s liarStore243) Update(uint32, func([]byte) error) error { return nil }\nfunc (s liarStore243) DiscardPrivate(uint32) error { return nil }\n\nfunc (s liarStore243) CopyPage(source, destination uint32, fn func(src, output []byte) error) error {\n\treturn fn(s.buf, s.buf)\n}\n\nfunc liarProbe243(page []byte) error {\n\tvar st tree.Store = liarStore243{}\n\treturn st.CopyPage(0, 1, func(src, output []byte) error {\n\t\tcopy(output, page)\n\t\treturn nil\n\t})\n}\n"}}},
	batteryCase{name: "B1: minted page export from internal/tree", desc: "tree mints and returns a full mapped page", expectFail: true, expectRule: "view-holder whitelist", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/tree/gatemut_mint.go", content: "package tree\n\nimport \"github.com/firehol/iprange/v4/go/internal/mapping\"\n\nfunc MintedPage(m *mapping.Mapping) ([]byte, error) {\n\treturn m.Page(0)\n}"}}},
	batteryCase{name: "B2: minted page export from a new package", desc: "a brand-new package mints and returns a full mapped page", expectFail: true, expectRule: "view-holder whitelist", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "gatemut_leak/mut.go", content: "package gatemut_leak\n\nimport \"github.com/firehol/iprange/v4/go/internal/mapping\"\n\nfunc Leak(m *mapping.Mapping) ([]byte, error) { return m.Page(0) }"}}},
	batteryCase{name: "B3: minted page export from internal/bitmap", desc: "bitmap mints and returns a full mapped page", expectFail: true, expectRule: "view-holder whitelist", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/bitmap/gatemut_mint.go", content: "package bitmap\n\nimport \"github.com/firehol/iprange/v4/go/internal/mapping\"\n\nfunc MintedPage(m *mapping.Mapping) ([]byte, error) {\n\treturn m.Page(0)\n}"}}},
	batteryCase{name: "B4: holder export of a mapped page stays benign", desc: "reader.page returns a mapped view; holders may export views", expectFail: false, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_holderexport.go", content: "package reader\n\nfunc HolderPage(r *ImmutableReader, pgno uint32) ([]byte, error) {\n\treturn r.page(pgno)\n}"}}},
	batteryCase{name: "B5: interface-method helper laundering a minted page", desc: "a non-holder helper calling m.Page(0) on an interface-typed receiver bound to a minted page: the unproven-callee result inherits the receiver provenance (an interface admitting the mapping owner fails closed on mapped) and the view-holder whitelist rejects the export (round-1 Sartre P2-1 shape; the type-parameter twin is covered by B8 since the memoized leaf walk, 2026-08-20)", expectFail: true, expectRule: "view-holder whitelist", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/tree/gatemut_generic.go", content: "package tree\n\nimport \"github.com/firehol/iprange/v4/go/internal/mapping\"\n\ntype pager5 interface{ Page(uint32) ([]byte, error) }\n\nfunc PeekC(m pager5) ([]byte, error) { return m.Page(0) }\n\nfunc LeakC(m *mapping.Mapping) ([]byte, error) { return PeekC(m) }"}}},
	batteryCase{name: "B8: type-parameter helper laundering a minted page", desc: "a non-holder generic helper calling m.Page(0) on a type-parameter receiver bound to a minted page: the unprovable-receiver rule rejects the call-site and the export fails closed. The type-parameter form previously drove the paramLeafPathsSeen walk divergence (SOW-0026); the memoized leaf walk (2026-08-20) terminates it", expectFail: true, expectRule: "m.Page on an unprovable receiver", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/tree/gatemut_genparam.go", content: "package tree\n\nimport \"github.com/firehol/iprange/v4/go/internal/mapping\"\n\ntype pagerT interface{ Page(uint32) ([]byte, error) }\n\nfunc PeekT[T interface{ Page(uint32) ([]byte, error) }](m T) ([]byte, error) {\n\treturn m.Page(0)\n}\n\nfunc LeakT(m *mapping.Mapping) ([]byte, error) { return PeekT(m) }"}}},
	batteryCase{name: "B6: public facade exporting a mapped page view", desc: "an exported module-root function returning a reader page view hands the mapping to application code; the root-boundary check must fail it (round-1 Sartre P2-2 shape)", expectFail: true, expectRule: "view-holder whitelist", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "internal/reader/gatemut_b6helper.go", content: "package reader\n\n// B6HolderPage exposes the mapped page view for the root-boundary probe.\nfunc (r *ImmutableReader) B6HolderPage(pgno uint32) ([]byte, error) {\n\treturn r.page(pgno)\n}"}, batteryOp{kind: "create", path: "zz_gatemut_root.go", content: "package iprangedb\n\n// RootPageBytes hands a mapped reader page view to application code.\nfunc RootPageBytes(r *ImmutableReader, pgno uint32) ([]byte, error) {\n\treturn r.inner.B6HolderPage(pgno)\n}"}}},
	batteryCase{name: "B7: public facade bounded export stays benign", desc: "an exported module-root function returning owned copied data stays legal under the root-boundary check (round-1 Sartre P2-2 honest twin)", expectFail: false, expectRule: "", allowTypeCheck: false, ops: []batteryOp{batteryOp{kind: "create", path: "zz_gatemut_root_benign.go", content: "package iprangedb\n\n// RootFeedName returns a copied name string, never a mapped view.\nfunc RootFeedName(r *ImmutableReader) string {\n\tentry, found, err := r.LookupFeed(\"feed-000\")\n\tif err != nil || !found {\n\t\treturn \"\"\n\t}\n\treturn entry.Name\n}"}}},
}
