// Command genfamilies emits the per-family concrete gap/replace layer
// of internal/tree (SOW-0027 regression slice I-1b): one generated file
// per range family (range_gap_v4.go, range_gap_v6.go) carrying the
// concrete probe, the concrete gap selector, and the family-specialized
// tree entries with the codec calls inlined - the Go equivalent of
// Rust's monomorphized fixed_tree/gap.rs over RangeCodec<Ipv4Key> and
// RangeCodec<Ipv6Key>. The template below is the single authoritative
// source of the emitted logic; edit the generator, not the output.
//
// Run with: go generate ./internal/tree
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"text/template"
)

// family is one emitted range family: type-name suffixes and the
// concrete key/codec/record types the emitted layer operates on.
type family struct {
	Suffix       string
	CodecType    string
	KeyType      string
	RecordType   string
	KeySize      int
	LowerBound   string
	LeafSizeExpr string
	AuxExpr      string
}

var families = []family{
	{Suffix: "4", CodecType: "RangeCodec4", KeyType: "RangeKey4", RecordType: "RangeRecord[RangeKey4]", KeySize: 4, LowerBound: "fixedLowerBoundU32", LeafSizeExpr: "format.RangeRecordV4Size", AuxExpr: "uint32(format.AddressFamilyIPv4)"},
	{Suffix: "6", CodecType: "RangeCodec6", KeyType: "RangeKey6", RecordType: "RangeRecord[RangeKey6]", KeySize: 16, LowerBound: "fixedLowerBoundU128", LeafSizeExpr: "format.RangeRecordV6Size", AuxExpr: "uint32(format.AddressFamilyIPv6)"},
}

var layer = template.Must(template.New("layer").Parse(`// Code generated by genfamilies; DO NOT EDIT.
//
// Family-specialized gap/replace layer (SOW-0027 regression slices
// I-1b and I-2): the concrete {{ .KeySize }}-byte {{ .CodecType }} probe,
// selector, descent, replacement application, and tree entries with the
// codec calls inlined, mirroring Rust's monomorphized fixed_tree/gap.rs
// over RangeCodec<Ipv4Key>/Ipv6Key. The single authoritative source is
// internal/tree/genfamilies; edit the generator, not this file.

package tree

import (
	"github.com/firehol/iprange/v4/go/internal/format"
	"github.com/firehol/iprange/v4/go/internal/work"
)

// rangeProbe{{ .Suffix }} is the concrete {{ .CodecType }} local-gap probe
// (Rust PrivateGap<RangeCodec<IpvXKey>>): every family operation is a
// direct call on the concrete codec, so one probe never dispatches
// through an interface.
type rangeProbe{{ .Suffix }} struct {
	codec {{ .CodecType }}
	r     {{ .RecordType }}
}

func (g rangeProbe{{ .Suffix }}) decode(cell []byte) ({{ .RecordType }}, error) {
	return g.codec.ReadLeaf(cell)
}

// Previous implements the LocalGap probe by value (Rust
// LocalGap::previous): the raw probing cell is returned so the selector
// decodes it once into the reject value.
func (g rangeProbe{{ .Suffix }}) Previous(exact bool, cell []byte) (LocalPrevious, []byte, error) {
	if cell == nil {
		return LocalPreviousAccept, nil, nil
	}
	previous, err := g.decode(cell)
	if err != nil {
		return 0, nil, err
	}
	bridges := false
	if next, ok := g.codec.Next(previous.To); ok {
		bridges = g.codec.Equal(next, g.r.From)
	}
	if exact || !g.codec.Less(previous.To, g.r.From) ||
		(previous.Value == g.r.Value && bridges) {
		return LocalPreviousReject, cell, nil
	}
	return LocalPreviousAccept, nil, nil
}

// Next implements the LocalGap probe by value (Rust LocalGap::next).
func (g rangeProbe{{ .Suffix }}) Next(cell []byte) (LocalNext, []byte, error) {
	if cell == nil {
		return LocalNextAccept, nil, nil
	}
	next, err := g.decode(cell)
	if err != nil {
		return 0, nil, err
	}
	bridges := false
	if boundary, ok := g.codec.Next(g.r.To); ok {
		bridges = g.codec.Equal(boundary, next.From)
	}
	if g.codec.Less(g.r.To, next.From) && (next.Value != g.r.Value || !bridges) {
		return LocalNextAccept, nil, nil
	}
	return LocalNextReject, cell, nil
}

// gapSelector{{ .Suffix }} is the concrete {{ .CodecType }} gap selector
// (Rust GapSelector<RangeCodec<IpvXKey>, PrivateGap<...>>).
type gapSelector{{ .Suffix }} struct {
	codec   {{ .CodecType }}
	key     Key
	cellLen int
	gap     rangeProbe{{ .Suffix }}
}

// selectAt decides the gap at one already-located position (Rust
// GapSelector::select_at).
func (g *gapSelector{{ .Suffix }}) selectAt(page []byte, header Header, path *Path, index int, exists bool) (gapDecision[{{ .RecordType }}], error) {
	predecessor, predecessorComplete, err := g.probePredecessor(page, header, path, index, exists)
	if err != nil {
		return gapDecision[{{ .RecordType }}]{}, err
	}
	successor, successorComplete, err := g.probeSuccessor(page, header, path, index, exists)
	if err != nil {
		return gapDecision[{{ .RecordType }}]{}, err
	}
	if predecessor.valid || successor.valid || !predecessorComplete || !successorComplete {
		return gapDecision[{{ .RecordType }}]{
			insert:              false,
			index:               index,
			predecessor:         predecessor,
			successor:           successor,
			predecessorComplete: predecessorComplete,
			successorComplete:   successorComplete,
		}, nil
	}
	return gapDecision[{{ .RecordType }}]{insert: true, index: index, fits: format.SlottedInsertFits(&header, g.cellLen)}, nil
}

func (g *gapSelector{{ .Suffix }}) probePredecessor(page []byte, header Header, path *Path, index int, exists bool) (rejectCell[{{ .RecordType }}], bool, error) {
	if exists {
		cell, err := g.validLeaf(page, header, index)
		if err != nil {
			return rejectCell[{{ .RecordType }}]{}, false, err
		}
		decision, raw, err := g.gap.Previous(true, cell)
		if err != nil {
			return rejectCell[{{ .RecordType }}]{}, false, err
		}
		if decision == LocalPreviousAccept {
			return rejectCell[{{ .RecordType }}]{}, false, corrupt("exact B+tree key was accepted as a gap")
		}
		value, err := g.codec.ReadLeaf(raw)
		if err != nil {
			return rejectCell[{{ .RecordType }}]{}, false, err
		}
		return rejectCell[{{ .RecordType }}]{index: index, value: value, valid: true}, true, nil
	}
	if index > 0 {
		cell, err := g.validLeaf(page, header, index-1)
		if err != nil {
			return rejectCell[{{ .RecordType }}]{}, false, err
		}
		decision, raw, err := g.gap.Previous(false, cell)
		if err != nil {
			return rejectCell[{{ .RecordType }}]{}, false, err
		}
		if decision == LocalPreviousAccept {
			return rejectCell[{{ .RecordType }}]{}, true, nil
		}
		value, err := g.codec.ReadLeaf(raw)
		if err != nil {
			return rejectCell[{{ .RecordType }}]{}, false, err
		}
		return rejectCell[{{ .RecordType }}]{index: index - 1, value: value, valid: true}, true, nil
	}
	if allFirst(path) {
		decision, _, err := g.gap.Previous(false, nil)
		if err != nil {
			return rejectCell[{{ .RecordType }}]{}, false, err
		}
		if decision == LocalPreviousReject {
			return rejectCell[{{ .RecordType }}]{}, false, corrupt("absent B+tree predecessor was rejected")
		}
		return rejectCell[{{ .RecordType }}]{}, true, nil
	}
	return rejectCell[{{ .RecordType }}]{}, false, nil
}

func (g *gapSelector{{ .Suffix }}) probeSuccessor(page []byte, header Header, path *Path, index int, exists bool) (rejectCell[{{ .RecordType }}], bool, error) {
	successorIndex := index
	if exists {
		successorIndex++
	}
	if successorIndex < int(header.ItemCount) {
		cell, err := g.validLeaf(page, header, successorIndex)
		if err != nil {
			return rejectCell[{{ .RecordType }}]{}, false, err
		}
		decision, raw, err := g.gap.Next(cell)
		if err != nil {
			return rejectCell[{{ .RecordType }}]{}, false, err
		}
		if decision == LocalNextAccept {
			return rejectCell[{{ .RecordType }}]{}, true, nil
		}
		value, err := g.codec.ReadLeaf(raw)
		if err != nil {
			return rejectCell[{{ .RecordType }}]{}, false, err
		}
		return rejectCell[{{ .RecordType }}]{index: successorIndex, value: value, valid: true}, true, nil
	}
	if allLast(path) {
		decision, _, err := g.gap.Next(nil)
		if err != nil {
			return rejectCell[{{ .RecordType }}]{}, false, err
		}
		if decision == LocalNextReject {
			return rejectCell[{{ .RecordType }}]{}, false, corrupt("absent B+tree successor was rejected")
		}
		return rejectCell[{{ .RecordType }}]{}, true, nil
	}
	return rejectCell[{{ .RecordType }}]{}, false, nil
}

// validLeaf re-verifies one leaf cell through the concrete codec (Rust
// validated_leaf): one SlottedCell read plus one ReadLeaf decode, no
// interface dispatch and no second decode anywhere else on the probe.
func (g gapSelector{{ .Suffix }}) validLeaf(page []byte, header Header, index int) ([]byte, error) {
	cell, err := format.SlottedCell(page, &header, index, g.codec.LeafSize())
	if err != nil {
		return nil, corrupt("slotted-page cell is outside the record area")
	}
	if _, err := g.codec.ReadLeaf(cell); err != nil {
		return nil, err
	}
	return cell, nil
}

// rangeCellSize{{ .Suffix }} is the fixed cell size of one
// {{ .CodecType }} tree level (Rust FixedCellSize): the range record on
// leaves, the key-plus-child entry on branches.
func rangeCellSize{{ .Suffix }}(level uint16) int {
	if level == 0 {
		return {{ .LeafSizeExpr }}
	}
	return {{ .KeySize }} + 4
}

// parseRange{{ .Suffix }} validates one slotted page of the family (the
// inlined form of parse: leaf/branch type and aux are family constants,
// so the type and discriminator checks fold to two compares).
func parseRange{{ .Suffix }}(page []byte, selectedTxn uint64, expectedLevel uint16, checkLevel bool) (Header, error) {
	work.PageParse(1)
	h, err := format.DecodePageHeader(page, selectedTxn)
	if err != nil {
		return Header{}, corrupt("slotted-page header is invalid: " + err.Error())
	}
	expectedType := format.PageTypeRangeLeaf
	if h.Level != 0 {
		expectedType = format.PageTypeRangeBranch
	}
	if h.PageType != expectedType || h.Aux != {{ .AuxExpr }} {
		return Header{}, corrupt("slotted-page type or discriminator is invalid")
	}
	if checkLevel && expectedLevel != h.Level {
		return Header{}, corrupt("slotted-page child level is invalid")
	}
	if !format.SlottedShapeValid(&h) {
		return Header{}, corrupt("slotted-page bounds are invalid")
	}
	return h, nil
}

// branchChild{{ .Suffix }} reads the child page number of one branch
// entry (the inlined form of branchChild: the entry is a fixed
// key-plus-child cell whose width is a family constant).
func branchChild{{ .Suffix }}(page []byte, header *Header, index int, pageLimit uint64) (uint32, error) {
	cell, err := format.SlottedCell(page, header, index, {{ .KeySize }}+4)
	if err != nil {
		return 0, corrupt("slotted-page cell is outside the record area")
	}
	child := format.U32(cell[{{ .KeySize }}:])
	if child < 2 || uint64(child) >= pageLimit {
		return 0, corrupt("B+tree child page is invalid")
	}
	return child, nil
}

// replaceBranchChild{{ .Suffix }} rewrites one branch slot to name a new
// child page (the inlined form of replaceBranchChild: the replacement
// entry is the old key bytes plus the new child number).
func replaceBranchChild{{ .Suffix }}(store Store, pageNumber uint32, index int, child uint32) error {
	targetTxn := store.TargetTxn()
	page, err := store.Inspect(pageNumber)
	if err != nil {
		return err
	}
	header, err := parseRange{{ .Suffix }}(page, targetTxn, 0, false)
	if err != nil {
		return err
	}
	cell, err := format.SlottedCell(page, &header, index, {{ .KeySize }}+4)
	if err != nil {
		return corrupt("slotted-page cell is outside the record area")
	}
	oldLen := len(cell)
	if _, err := branchChild{{ .Suffix }}(page, &header, index, store.PageLimit()); err != nil {
		return err
	}
	var replacement [{{ .KeySize }} + 4]byte
	copy(replacement[:{{ .KeySize }}], cell[:{{ .KeySize }}])
	format.PutU32(replacement[{{ .KeySize }}:], child)
	page, tag, err := store.Update(pageNumber)
	if err != nil {
		return err
	}
	ok, err := format.SlottedReplace(page, &header, index, oldLen, replacement[:])
	if err != nil {
		return err
	}
	if !ok {
		return corrupt("B+tree child replacement no longer fits")
	}
	return store.RestoreDirty(pageNumber, tag)
}

// privateRangePath{{ .Suffix }} descends from the root, privatizing every
// committed page along the path (the inlined form of privatePathSelect:
// page validation, the fixed-key search, and the branch-child decode are
// family constants; the COW touch stays shared).
func privateRangePath{{ .Suffix }}(store Store, root *uint32, key Key, retired RetiredPages) (PrivateLeaf, RetiredPages, error) {
	work.TreeLookup(1)
	var path Path
	pageNumber := *root
	var expectedLevel uint16
	checkLevel := false
	hasParent := false
	parentPage := uint32(0)
	parentIndex := 0

	for {
		page, err := store.Inspect(pageNumber)
		if err != nil {
			return PrivateLeaf{}, RetiredPages{}, err
		}
		header, err := parseRange{{ .Suffix }}(page, store.TargetTxn(), expectedLevel, checkLevel)
		if err != nil {
			return PrivateLeaf{}, RetiredPages{}, err
		}
		born := format.U64(page[format.HeaderBorn:])
		if header.Level == 0 {
			activePage := pageNumber
			if born != store.TargetTxn() {
				copied, err := touch(store, pageNumber, &retired)
				if err != nil {
					return PrivateLeaf{}, RetiredPages{}, err
				}
				activePage = copied
				if hasParent {
					if err := replaceBranchChild{{ .Suffix }}(store, parentPage, parentIndex, copied); err != nil {
						return PrivateLeaf{}, RetiredPages{}, err
					}
				} else {
					*root = copied
				}
				// The leaf moved to a fresh private page; re-inspect it.
				// The private page view is required for the caller's
				// selection, and the source mapping view may be a growth
				// or COW buffer the draft no longer owns.
				if page, err = store.Inspect(copied); err != nil {
					return PrivateLeaf{}, RetiredPages{}, err
				}
				if header, err = parseRange{{ .Suffix }}(page, store.TargetTxn(), expectedLevel, checkLevel); err != nil {
					return PrivateLeaf{}, RetiredPages{}, err
				}
			}
			return PrivateLeaf{Path: path, PageNumber: activePage, Header: header, Page: page}, retired, nil
		}
		index, _, err := {{ .LowerBound }}(page, &header, rangeCellSize{{ .Suffix }}(header.Level), key, false)
		if err != nil {
			return PrivateLeaf{}, RetiredPages{}, err
		}
		child, err := branchChild{{ .Suffix }}(page, &header, index, store.PageLimit())
		if err != nil {
			return PrivateLeaf{}, RetiredPages{}, err
		}
		activePage := pageNumber
		if born != store.TargetTxn() {
			copied, err := touch(store, pageNumber, &retired)
			if err != nil {
				return PrivateLeaf{}, RetiredPages{}, err
			}
			activePage = copied
			if hasParent {
				if err := replaceBranchChild{{ .Suffix }}(store, parentPage, parentIndex, copied); err != nil {
					return PrivateLeaf{}, RetiredPages{}, err
				}
			} else {
				*root = copied
			}
		}
		if err := path.Push(Frame{PageNumber: activePage, Index: index, ItemCount: int(header.ItemCount)}); err != nil {
			return PrivateLeaf{}, RetiredPages{}, err
		}
		hasParent = true
		parentPage = activePage
		parentIndex = index
		pageNumber = child
		expectedLevel = header.Level - 1
		checkLevel = true
		work.TreeDescent(1)
	}
}

// replacementFits{{ .Suffix }} reports whether a 2-3 cell replacement
// fits in one leaf (the inlined form of replacementFits: the replaced
// cell width is a family constant).
func replacementFits{{ .Suffix }}(page []byte, header *Header, edit Replacement) (bool, error) {
	work.EditFitProbe(1)
	if edit.index >= int(header.ItemCount) || len(edit.cells) == 0 {
		return false, corrupt("B+tree replacement is invalid")
	}
	oldCell, err := format.SlottedCell(page, header, edit.index, rangeCellSize{{ .Suffix }}(header.Level))
	if err != nil {
		return false, corrupt("slotted-page cell is outside the record area")
	}
	available := len(oldCell) + int(header.Upper-header.Lower)
	payload := 0
	for _, cell := range edit.cells {
		payload += len(cell)
	}
	required := payload + (len(edit.cells)-1)*2
	return required <= available, nil
}

// applyCells{{ .Suffix }} applies one 2-3 cell replacement to a private
// leaf (the inlined form of applyCells: parse and cell widths are
// family constants).
func applyCells{{ .Suffix }}(page []byte, header *Header, index int, cells [][]byte) error {
	oldCell, err := format.SlottedCell(page, header, index, rangeCellSize{{ .Suffix }}(header.Level))
	if err != nil {
		return corrupt("slotted-page cell is outside the record area")
	}
	ok, err := format.SlottedReplace(page, header, index, len(oldCell), cells[0])
	if err != nil {
		return err
	}
	if !ok {
		return corrupt("B+tree replacement no longer fits")
	}
	for offset, cell := range cells[1:] {
		current, err := parseRange{{ .Suffix }}(page, ^uint64(0), header.Level, true)
		if err != nil {
			return err
		}
		ok, err := format.SlottedInsert(page, &current, index+offset+1, cell)
		if err != nil {
			return err
		}
		if !ok {
			return corrupt("B+tree replacement insertion no longer fits")
		}
	}
	return nil
}

// applyReplacement{{ .Suffix }} applies one leaf replacement, splitting
// when it does not fit (the inlined form of applyReplacement; the rare
// split path keeps the generic reference machinery).
func applyReplacement{{ .Suffix }}(codec {{ .CodecType }}, store Store, pageNumber uint32, header *Header, edit Replacement) (branchSplit, bool, error) {
	page, err := store.Inspect(pageNumber)
	if err != nil {
		return branchSplit{}, false, err
	}
	fits, err := replacementFits{{ .Suffix }}(page, header, edit)
	if err != nil {
		return branchSplit{}, false, err
	}
	if fits {
		page, tag, err := store.Update(pageNumber)
		if err != nil {
			return branchSplit{}, false, err
		}
		if err := applyCells{{ .Suffix }}(page, header, edit.index, edit.cells); err != nil {
			return branchSplit{}, false, err
		}
		return branchSplit{}, false, store.RestoreDirty(pageNumber, tag)
	}
	return splitReplacement(codec, store, pageNumber, header, edit)
}

// replaceTarget{{ .Suffix }} replaces one leaf cell with 2-3 cells and
// propagates the resulting split (the inlined form of replaceTarget;
// the split path keeps the generic propagation).
func replaceTarget{{ .Suffix }}(codec {{ .CodecType }}, store Store, root *uint32, target LeafTarget, cells [][]byte) error {
	edit := Replacement{index: target.Index, cells: cells}
	split, ok, err := applyReplacement{{ .Suffix }}(codec, store, target.PageNumber, &target.Header, edit)
	if err != nil {
		return err
	}
	if !ok {
		return nil
	}
	if split.level != 0 {
		return corrupt("B+tree leaf replacement changed level")
	}
	return propagateSplit(codec, store, root, &target.Path, target.PageNumber, split.leftFirst, split.rightPage, split.rightFirst, 0)
}

// InsertIfLocalGap{{ .Suffix }} inserts one leaf cell into the physical gap
// around its key when the gap is fully local to the probed leaf (Rust
// insert_if_local_gap; the family-specialized form of InsertIfLocalGap
// that the writer routes to).
func InsertIfLocalGap{{ .Suffix }}(codec {{ .CodecType }}, store Store, root *uint32, leafCell []byte, retired RetiredPages, r {{ .RecordType }}) (RetiredPages, LocalInsert[{{ .RecordType }}], error) {
	gap := rangeProbe{{ .Suffix }}{codec: codec, r: r}
	if err := RequireLeaf(codec, leafCell); err != nil {
		return RetiredPages{}, LocalInsert[{{ .RecordType }}]{}, err
	}
	if *root == 0 {
		pageNumber, err := NewLeaf(codec, store, leafCell)
		if err != nil {
			return RetiredPages{}, LocalInsert[{{ .RecordType }}]{}, err
		}
		*root = pageNumber
		return retired, LocalInsert[{{ .RecordType }}]{Inserted: true, PageNumber: pageNumber}, nil
	}
	key, err := codec.ReadKey(leafCell, 0)
	if err != nil {
		return RetiredPages{}, LocalInsert[{{ .RecordType }}]{}, err
	}
	leaf, retired, err := privateRangePath{{ .Suffix }}(store, root, key, retired)
	if err != nil {
		return RetiredPages{}, LocalInsert[{{ .RecordType }}]{}, err
	}
	if retired.Len() != 0 {
		return RetiredPages{}, LocalInsert[{{ .RecordType }}]{}, corrupt("private B+tree contains a committed page")
	}
	header := leaf.Header
	selector := gapSelector{{ .Suffix }}{codec: codec, key: key, cellLen: len(leafCell), gap: gap}
	index, exists, err := {{ .LowerBound }}(leaf.Page, &header, rangeCellSize{{ .Suffix }}(0), key, true)
	if err != nil {
		return RetiredPages{}, LocalInsert[{{ .RecordType }}]{}, err
	}
	decision, err := selector.selectAt(leaf.Page, header, &leaf.Path, index, exists)
	if err != nil {
		return RetiredPages{}, LocalInsert[{{ .RecordType }}]{}, err
	}
	if !decision.insert {
		reject, err := rejection(leaf.Path, leaf.PageNumber, leaf.Header, decision)
		if err != nil {
			return RetiredPages{}, LocalInsert[{{ .RecordType }}]{}, err
		}
		return retired, LocalInsert[{{ .RecordType }}]{Reject: reject, Rejected: true}, nil
	}
	target := LeafTarget{Path: leaf.Path, PageNumber: leaf.PageNumber, Header: leaf.Header, Index: decision.index, Exists: false}
	pageNumber := target.PageNumber
	positioned, fits, err := insertGapTarget(codec, store, root, leafCell, target, key, decision.fits)
	if err != nil {
		return RetiredPages{}, LocalInsert[{{ .RecordType }}]{}, err
	}
	if fits {
		pageNumber = positioned.PageNumber
	}
	return retired, LocalInsert[{{ .RecordType }}]{Inserted: true, PageNumber: pageNumber}, nil
}

// InsertIfCachedInteriorGap{{ .Suffix }} probes one cached private leaf for a
// fitting interior gap and inserts the cell there (Rust
// insert_if_cached_interior_gap; the family-specialized form of
// InsertIfCachedInteriorGap).
func InsertIfCachedInteriorGap{{ .Suffix }}(codec {{ .CodecType }}, store Store, pageNumber uint32, leafCell []byte, r {{ .RecordType }}) (CachedInsert, error) {
	gap := rangeProbe{{ .Suffix }}{codec: codec, r: r}
	if err := RequireLeaf(codec, leafCell); err != nil {
		return CachedInsertMiss, err
	}
	key, err := codec.ReadKey(leafCell, 0)
	if err != nil {
		return CachedInsertMiss, err
	}
	level := uint16(0)
	page, err := store.Inspect(pageNumber)
	if err != nil {
		return CachedInsertMiss, err
	}
	header, err := parse(codec, page, store.TargetTxn(), level, true)
	if err != nil {
		return CachedInsertMiss, err
	}
	if format.U64(page[format.HeaderBorn:]) != store.TargetTxn() {
		return CachedInsertMiss, corrupt("leaf locator selected a committed page")
	}
	probeIndex, exists, err := lowerBound(codec, page, &header, key, true)
	if err != nil {
		return CachedInsertMiss, err
	}
	if exists || probeIndex == 0 || probeIndex == int(header.ItemCount) {
		return CachedInsertMiss, nil
	}
	selector := gapSelector{{ .Suffix }}{codec: codec, key: key, cellLen: len(leafCell), gap: gap}
	decision, err := selector.selectAt(page, header, nil, probeIndex, false)
	if err != nil {
		return CachedInsertMiss, err
	}
	if !decision.insert || !decision.fits {
		return CachedInsertMiss, nil
	}
	return CachedInsertInserted, applyLeafEdit(codec, store, pageNumber, &header, Edit{index: decision.index, replace: false, cell: leafCell})
}

// InsertIfEdgeGap{{ .Suffix }} inserts one leaf cell at a cached private
// tree edge when the local gap is open (Rust insert_if_edge_gap; the
// family-specialized form of InsertIfEdgeGap).
func InsertIfEdgeGap{{ .Suffix }}(codec {{ .CodecType }}, store Store, root *uint32, leafCell []byte, cached *PrivateEdge, edge Edge, knownGap bool, r {{ .RecordType }}) (EdgeInsert[{{ .RecordType }}], error) {
	gap := rangeProbe{{ .Suffix }}{codec: codec, r: r}
	if err := RequireLeaf(codec, leafCell); err != nil {
		return EdgeInsert[{{ .RecordType }}]{}, err
	}
	if *root == 0 {
		return EdgeInsert[{{ .RecordType }}]{}, corrupt("cached B+tree edge has an empty root")
	}
	if err := verifyCachedEdge(cached, *root, edge); err != nil {
		return EdgeInsert[{{ .RecordType }}]{}, err
	}
	key, err := codec.ReadKey(leafCell, 0)
	if err != nil {
		return EdgeInsert[{{ .RecordType }}]{}, err
	}
	level := uint16(0)
	page, err := store.Inspect(cached.position.PageNumber)
	if err != nil {
		return EdgeInsert[{{ .RecordType }}]{}, err
	}
	header, err := parse(codec, page, store.TargetTxn(), level, true)
	if err != nil {
		return EdgeInsert[{{ .RecordType }}]{}, err
	}
	if format.U64(page[format.HeaderBorn:]) != store.TargetTxn() {
		return EdgeInsert[{{ .RecordType }}]{}, corrupt("cached B+tree edge is not private")
	}
	boundary := 0
	if edge == EdgeLast {
		boundary = int(header.ItemCount) - 1
	}
	boundaryKey, err := keyAt(codec, page, &header, boundary)
	if err != nil {
		return EdgeInsert[{{ .RecordType }}]{}, err
	}
	index := 0
	exists := false
	if edge == EdgeFirst {
		switch {
		case key.Less(boundaryKey):
			index, exists = 0, false
		case key.Equal(boundaryKey):
			index, exists = 0, true
		default:
			return EdgeInsert[{{ .RecordType }}]{}, corrupt("cached B+tree edge order changed")
		}
	} else {
		switch {
		case boundaryKey.Less(key):
			index, exists = int(header.ItemCount), false
		case key.Equal(boundaryKey):
			index, exists = int(header.ItemCount)-1, true
		default:
			return EdgeInsert[{{ .RecordType }}]{}, corrupt("cached B+tree edge order changed")
		}
	}
	var decision gapDecision[{{ .RecordType }}]
	if knownGap {
		if exists {
			return EdgeInsert[{{ .RecordType }}]{}, corrupt("known B+tree edge gap contains its key")
		}
		decision = gapDecision[{{ .RecordType }}]{insert: true, index: index, fits: format.SlottedInsertFits(&header, len(leafCell))}
	} else {
		selector := gapSelector{{ .Suffix }}{codec: codec, key: key, cellLen: len(leafCell), gap: gap}
		decision, err = selector.selectAt(page, header, &cached.position.Path, index, exists)
		if err != nil {
			return EdgeInsert[{{ .RecordType }}]{}, err
		}
	}
	if !decision.insert {
		if err := FlushEdge(codec, store, root, cached); err != nil {
			return EdgeInsert[{{ .RecordType }}]{}, err
		}
		reject, err := rejection(cached.position.Path, cached.position.PageNumber, header, decision)
		if err != nil {
			return EdgeInsert[{{ .RecordType }}]{}, err
		}
		return EdgeInsert[{{ .RecordType }}]{Reject: reject, Rejected: true}, nil
	}
	target := LeafTarget{Path: cached.position.Path, PageNumber: cached.position.PageNumber, Header: header, Index: decision.index, Exists: false}
	if decision.fits {
		var pendingFirst Key
		hasPendingFirst := false
		if target.Index == 0 && target.Path.Depth() != 0 {
			pendingFirst = key
			hasPendingFirst = true
		}
		position, err := applyFittingEdgeInsert(codec, store, target, leafCell)
		if err != nil {
			return EdgeInsert[{{ .RecordType }}]{}, err
		}
		cached.position = position
		if hasPendingFirst {
			cached.pendingFirst = pendingFirst
			cached.hasPendingFirst = true
		} else {
			cached.hasPendingFirst = false
		}
	} else {
		if err := SplitLeafAtEdge(codec, store, root, &target, leafCell, edge); err != nil {
			return EdgeInsert[{{ .RecordType }}]{}, err
		}
		cached.hasPendingFirst = false
		position, err := locatePrivatePosition(codec, store, root, key)
		if err != nil {
			return EdgeInsert[{{ .RecordType }}]{}, err
		}
		cached.position = position
	}
	return EdgeInsert[{{ .RecordType }}]{Inserted: true, Edge: cached}, nil
}

// InsertRejectedGap{{ .Suffix }} completes a previously rejected local gap
// insertion after the caller proved the external sides (Rust
// insert_rejected_gap; the family-specialized form of
// InsertRejectedGap).
func InsertRejectedGap{{ .Suffix }}(codec {{ .CodecType }}, store Store, root *uint32, leafCell []byte, rejected LocalReject[{{ .RecordType }}]) (PrivatePosition, bool, error) {
	if err := RequireLeaf(codec, leafCell); err != nil {
		return PrivatePosition{}, false, err
	}
	key, err := codec.ReadKey(leafCell, 0)
	if err != nil {
		return PrivatePosition{}, false, err
	}
	fits := format.SlottedInsertFits(&rejected.Target.Header, len(leafCell))
	return insertGapTarget(codec, store, root, leafCell, rejected.Target, key, fits)
}

// requireReplacement{{ .Suffix }} is the concrete limb form of
// RequireReplacement (Rust require_replacement over the fixed key
// type): the cells carry the width-fixed little-endian order key, so
// the limb pairs compare directly and no general tree key is built.
func requireReplacement{{ .Suffix }}(codec {{ .CodecType }}, key Key, cells [][]byte) error {
	if len(cells) < 2 || len(cells) > 3 {
		return invalid("B+tree leaf replacement requires two or three cells")
	}
	var firstHi, firstLo uint64
	var previousHi, previousLo uint64
	for index, cell := range cells {
		if err := RequireLeaf(codec, cell); err != nil {
			return err
		}
		hi, lo, err := codec.ReadKeyLimbs(cell)
		if err != nil {
			return err
		}
		if index == 0 {
			firstHi, firstLo = hi, lo
		} else if previousHi > hi || (previousHi == hi && previousLo >= lo) {
			return invalid("B+tree replacement keys are not increasing")
		}
		previousHi, previousLo = hi, lo
	}
	if firstHi != key.hi || firstLo != key.lo {
		return invalid("B+tree replacement changed its first key")
	}
	return nil
}

// ReplaceLocalPredecessorWith{{ .Suffix }} replaces the rejected gap's local
// predecessor cell with a 2-3 cell replacement (Rust
// replace_local_predecessor_with; the family-specialized form of
// ReplaceLocalPredecessorWith).
func ReplaceLocalPredecessorWith{{ .Suffix }}(codec {{ .CodecType }}, store Store, root *uint32, rejected LocalReject[{{ .RecordType }}], key Key, cells [][]byte) error {
	if err := requireReplacement{{ .Suffix }}(codec, key, cells); err != nil {
		return err
	}
	if !rejected.predecessor.valid {
		return corrupt("B+tree local predecessor is unavailable")
	}
	target := rejected.Target
	target.Index = rejected.predecessorIndex()
	target.Exists = true
	return replaceTarget{{ .Suffix }}(codec, store, root, target, cells)
}

// ReplaceLocalRun{{ .Suffix }} overwrites one local neighbor cell (or the
// contiguous pair) of a rejected gap with one replacement cell (Rust
// replace_local_run; the family-specialized form of ReplaceLocalRun).
func ReplaceLocalRun{{ .Suffix }}(codec {{ .CodecType }}, store Store, root *uint32, rejected LocalReject[{{ .RecordType }}], run LocalRun, replacement []byte) error {
	if err := RequireLeaf(codec, replacement); err != nil {
		return err
	}
	start := 0
	removeCount := 1
	switch run {
	case LocalRunPredecessor:
		if !rejected.predecessor.valid {
			return corrupt("local predecessor is unavailable")
		}
		start = rejected.predecessorIndex()
	case LocalRunSuccessor:
		if !rejected.successor.valid {
			return corrupt("local successor is unavailable")
		}
		start = rejected.successorIndex()
	case LocalRunBoth:
		if !rejected.predecessor.valid {
			return corrupt("local predecessor is unavailable")
		}
		if !rejected.successor.valid {
			return corrupt("local successor is unavailable")
		}
		if rejected.successorIndex() != rejected.predecessorIndex()+1 {
			return corrupt("local B+tree run is not contiguous")
		}
		start = rejected.predecessorIndex()
		removeCount = 2
	}
	target := &rejected.Target
	if start+removeCount > int(target.Header.ItemCount) {
		return corrupt("local B+tree run is outside its leaf")
	}
	replacementKey, err := codec.ReadKey(replacement, 0)
	if err != nil {
		return err
	}
	page, tag, err := store.Update(target.PageNumber)
	if err != nil {
		return err
	}
	oldLen, err := format.SlottedCell(page, &target.Header, start, codec.LeafSize())
	if err != nil {
		return corrupt("slotted-page cell is outside the record area")
	}
	oldLenBytes := len(oldLen)
	if len(replacement) != oldLenBytes {
		return unsupported("local B+tree run replacement changed cell size")
	}
	if start > 0 {
		previous, err := keyAt(codec, page, &target.Header, start-1)
		if err != nil {
			return err
		}
		if !previous.Less(replacementKey) {
			return corrupt("local B+tree replacement is out of order")
		}
	}
	if start+removeCount < int(target.Header.ItemCount) {
		next, err := keyAt(codec, page, &target.Header, start+removeCount)
		if err != nil {
			return err
		}
		if !replacementKey.Less(next) {
			return corrupt("local B+tree replacement is out of order")
		}
	}
	changed, err := format.SlottedReplace(page, &target.Header, start, oldLenBytes, replacement)
	if err != nil {
		return err
	}
	if !changed {
		return corrupt("local B+tree replacement no longer fits")
	}
	header := target.Header
	for i := 1; i < removeCount; i++ {
		cell, err := format.SlottedCell(page, &header, start+1, codec.LeafSize())
		if err != nil {
			return corrupt("slotted-page cell is outside the record area")
		}
		if err := format.SlottedRemove(page, &header, start+1, len(cell)); err != nil {
			return err
		}
		header.ItemCount--
		header.Lower -= 2
		header.Upper += uint16(len(cell))
	}
	if err := store.RestoreDirty(target.PageNumber, tag); err != nil {
		return err
	}
	if start == 0 {
		if err := PropagateFirst(codec, store, root, &target.Path, replacementKey); err != nil {
			return err
		}
	}
	return nil
}

var _ = work.KeyProbe
`))

func main() {
	for _, f := range families {
		var out bytes.Buffer
		if err := layer.Execute(&out, f); err != nil {
			fmt.Fprintln(os.Stderr, "genfamilies:", err)
			os.Exit(1)
		}
		src, err := format.Source(out.Bytes())
		if err != nil {
			fmt.Fprintln(os.Stderr, "genfamilies: go/format:", err)
			os.Exit(1)
		}
		target := resolveTarget(f.Suffix)
		if err := os.WriteFile(target, src, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "genfamilies:", err)
			os.Exit(1)
		}
		fmt.Println("genfamilies: wrote", target)
	}
}

// resolveTarget places the emitted file next to the package regardless
// of whether the generator runs from the package directory (go
// generate) or from the module root.
func resolveTarget(suffix string) string {
	target := "range_gap_v" + suffix + ".go"
	if base := filepath.Base(mustCwd()); base != "tree" {
		target = filepath.Join("internal", "tree", target)
	}
	return target
}

func mustCwd() string {
	dir, err := os.Getwd()
	if err != nil {
		fmt.Fprintln(os.Stderr, "genfamilies:", err)
		os.Exit(1)
	}
	return dir
}
