//go:build !windows

// Differential golden test: pathname semantics against rustc
// 1.97.1 std::path (Path::file_name, Path::parent,
// PathBuf::with_file_name) on a 162-shape corpus. Generated from a
// native Linux probe; the Windows corpus is the
// golden_windows_test.go twin produced on the Windows host.
package pathname

import "testing"

type goldenRow struct {
	shape    string
	name     string // quoted name, or "" with ok=false
	nameOK   bool
	parent   string
	parentOK bool
	wf       string
}

func TestRustGoldenUnix(t *testing.T) {
	rows := []goldenRow{
		{shape: "", name: "", nameOK: false, parent: "", parentOK: false, wf: "N.readers"},
		{shape: ".", name: "", nameOK: false, parent: "", parentOK: true, wf: "./N.readers"},
		{shape: "..", name: "", nameOK: false, parent: "", parentOK: true, wf: "../N.readers"},
		{shape: "a", name: "a", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a/", name: "a", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a/.", name: "a", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a/..", name: "", nameOK: false, parent: "a", parentOK: true, wf: "a/../N.readers"},
		{shape: "a/b", name: "b", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/b/", name: "b", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/b/.", name: "b", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/b/..", name: "", nameOK: false, parent: "a/b", parentOK: true, wf: "a/b/../N.readers"},
		{shape: "a/b/../", name: "", nameOK: false, parent: "a/b", parentOK: true, wf: "a/b/../N.readers"},
		{shape: "a/../b", name: "b", nameOK: true, parent: "a/..", parentOK: true, wf: "a/../N.readers"},
		{shape: "a/../b/", name: "b", nameOK: true, parent: "a/..", parentOK: true, wf: "a/../N.readers"},
		{shape: "../a", name: "a", nameOK: true, parent: "..", parentOK: true, wf: "../N.readers"},
		{shape: "../..", name: "", nameOK: false, parent: "..", parentOK: true, wf: "../../N.readers"},
		{shape: "a/../..", name: "", nameOK: false, parent: "a/..", parentOK: true, wf: "a/../../N.readers"},
		{shape: "x/..", name: "", nameOK: false, parent: "x", parentOK: true, wf: "x/../N.readers"},
		{shape: "x/../..", name: "", nameOK: false, parent: "x/..", parentOK: true, wf: "x/../../N.readers"},
		{shape: "/", name: "", nameOK: false, parent: "", parentOK: false, wf: "/N.readers"},
		{shape: "//", name: "", nameOK: false, parent: "", parentOK: false, wf: "//N.readers"},
		{shape: "/a", name: "a", nameOK: true, parent: "/", parentOK: true, wf: "/N.readers"},
		{shape: "/a/", name: "a", nameOK: true, parent: "/", parentOK: true, wf: "/N.readers"},
		{shape: "/a/.", name: "a", nameOK: true, parent: "/", parentOK: true, wf: "/N.readers"},
		{shape: "/a/..", name: "", nameOK: false, parent: "/a", parentOK: true, wf: "/a/../N.readers"},
		{shape: "/a/b", name: "b", nameOK: true, parent: "/a", parentOK: true, wf: "/a/N.readers"},
		{shape: "/a/b/..", name: "", nameOK: false, parent: "/a/b", parentOK: true, wf: "/a/b/../N.readers"},
		{shape: "/a/../b", name: "b", nameOK: true, parent: "/a/..", parentOK: true, wf: "/a/../N.readers"},
		{shape: "/a/b/c", name: "c", nameOK: true, parent: "/a/b", parentOK: true, wf: "/a/b/N.readers"},
		{shape: "a//b", name: "b", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a///b//c", name: "c", nameOK: true, parent: "a///b", parentOK: true, wf: "a///b/N.readers"},
		{shape: "a/./b", name: "b", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "./a", name: "a", nameOK: true, parent: ".", parentOK: true, wf: "./N.readers"},
		{shape: "a/./.", name: "a", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a/./b/.", name: "b", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "...", name: "...", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "..foo", name: "..foo", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "..git", name: "..git", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a/..foo", name: "..foo", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "dir/..file", name: "..file", nameOK: true, parent: "dir", parentOK: true, wf: "dir/N.readers"},
		{shape: "a/b/...", name: "...", nameOK: true, parent: "a/b", parentOK: true, wf: "a/b/N.readers"},
		{shape: "a/b/.../..", name: "", nameOK: false, parent: "a/b/...", parentOK: true, wf: "a/b/.../../N.readers"},
		{shape: "a/.readers", name: ".readers", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/x.readers", name: "x.readers", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/.iprange-x", name: ".iprange-x", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/iprange-x", name: "iprange-x", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a b", name: "a b", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a\tb", name: "a\tb", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a\\b", name: "a\\b", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a/b\\c", name: "b\\c", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/--", name: "--", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/-", name: "-", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "-", name: "-", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "--", name: "--", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a.-", name: "a.-", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a-.b", name: "a-.b", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "C:", name: "C:", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "C:/", name: "C:", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "C:/a", name: "a", nameOK: true, parent: "C:", parentOK: true, wf: "C:/N.readers"},
		{shape: "C:/a/b", name: "b", nameOK: true, parent: "C:/a", parentOK: true, wf: "C:/a/N.readers"},
		{shape: "C:/a/..", name: "", nameOK: false, parent: "C:/a", parentOK: true, wf: "C:/a/../N.readers"},
		{shape: "C:/a/.", name: "a", nameOK: true, parent: "C:", parentOK: true, wf: "C:/N.readers"},
		{shape: "C:a", name: "C:a", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "C:a/b", name: "b", nameOK: true, parent: "C:a", parentOK: true, wf: "C:a/N.readers"},
		{shape: "C:/", name: "C:", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "C:/.", name: "C:", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "C:..", name: "C:..", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "C:a/..", name: "", nameOK: false, parent: "C:a", parentOK: true, wf: "C:a/../N.readers"},
		{shape: "C:/a/../..", name: "", nameOK: false, parent: "C:/a/..", parentOK: true, wf: "C:/a/../../N.readers"},
		{shape: "C:a/.", name: "C:a", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "C:.", name: "C:.", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "C:.", name: "C:.", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "//server/share", name: "share", nameOK: true, parent: "//server", parentOK: true, wf: "//server/N.readers"},
		{shape: "//server/share/", name: "share", nameOK: true, parent: "//server", parentOK: true, wf: "//server/N.readers"},
		{shape: "//server/share/a", name: "a", nameOK: true, parent: "//server/share", parentOK: true, wf: "//server/share/N.readers"},
		{shape: "//server/share/a/..", name: "", nameOK: false, parent: "//server/share/a", parentOK: true, wf: "//server/share/a/../N.readers"},
		{shape: "//server/share/a/.", name: "a", nameOK: true, parent: "//server/share", parentOK: true, wf: "//server/share/N.readers"},
		{shape: "\\", name: "\\", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "\\a", name: "\\a", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "\\a\\b", name: "\\a\\b", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a\\", name: "a\\", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a\\..", name: "a\\..", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a\\b\\..", name: "a\\b\\..", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a/b\\c/d", name: "d", nameOK: true, parent: "a/b\\c", parentOK: true, wf: "a/b\\c/N.readers"},
		{shape: "x\\y/z/..", name: "", nameOK: false, parent: "x\\y/z", parentOK: true, wf: "x\\y/z/../N.readers"},
		{shape: "x\\.y", name: "x\\.y", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "x/y./", name: "y.", nameOK: true, parent: "x", parentOK: true, wf: "x/N.readers"},
		{shape: "x/y../", name: "y..", nameOK: true, parent: "x", parentOK: true, wf: "x/N.readers"},
		{shape: "..a", name: "..a", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a..", name: "a..", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a.b", name: "a.b", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a/.b", name: ".b", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/..b/c", name: "c", nameOK: true, parent: "a/..b", parentOK: true, wf: "a/..b/N.readers"},
		{shape: "a/b/.c", name: ".c", nameOK: true, parent: "a/b", parentOK: true, wf: "a/b/N.readers"},
		{shape: "a/b/..c", name: "..c", nameOK: true, parent: "a/b", parentOK: true, wf: "a/b/N.readers"},
		{shape: "a/b/c..", name: "c..", nameOK: true, parent: "a/b", parentOK: true, wf: "a/b/N.readers"},
		{shape: "a/b/.c.", name: ".c.", nameOK: true, parent: "a/b", parentOK: true, wf: "a/b/N.readers"},
		{shape: "/a/b/./../c", name: "c", nameOK: true, parent: "/a/b/./..", parentOK: true, wf: "/a/b/./../N.readers"},
		{shape: "a/b/./../c", name: "c", nameOK: true, parent: "a/b/./..", parentOK: true, wf: "a/b/./../N.readers"},
		{shape: "a/b/./../..", name: "", nameOK: false, parent: "a/b/./..", parentOK: true, wf: "a/b/./../../N.readers"},
		{shape: "/a/b/./../..", name: "", nameOK: false, parent: "/a/b/./..", parentOK: true, wf: "/a/b/./../../N.readers"},
		{shape: "a/./../b/..", name: "", nameOK: false, parent: "a/./../b", parentOK: true, wf: "a/./../b/../N.readers"},
		{shape: "a/..b", name: "..b", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/b/..c/..d", name: "..d", nameOK: true, parent: "a/b/..c", parentOK: true, wf: "a/b/..c/N.readers"},
		{shape: ".hidden", name: ".hidden", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "..hidden", name: "..hidden", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a/.../..", name: "", nameOK: false, parent: "a/...", parentOK: true, wf: "a/.../../N.readers"},
		{shape: "a/....", name: "....", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/.....", name: ".....", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/.../b", name: "b", nameOK: true, parent: "a/...", parentOK: true, wf: "a/.../N.readers"},
		{shape: "C:/a/.readers", name: ".readers", nameOK: true, parent: "C:/a", parentOK: true, wf: "C:/a/N.readers"},
		{shape: "C:/a/..", name: "", nameOK: false, parent: "C:/a", parentOK: true, wf: "C:/a/../N.readers"},
		{shape: "a/", name: "a", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "/", name: "", nameOK: false, parent: "", parentOK: false, wf: "/N.readers"},
		{shape: "./", name: "", nameOK: false, parent: "", parentOK: true, wf: "./N.readers"},
		{shape: "../", name: "", nameOK: false, parent: "", parentOK: true, wf: "../N.readers"},
		{shape: "a/b/", name: "b", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "/a/b/", name: "b", nameOK: true, parent: "/a", parentOK: true, wf: "/a/N.readers"},
		{shape: "C:/", name: "C:", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "C:\\", name: "C:\\", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "C:\\a", name: "C:\\a", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "C:\\a\\..", name: "C:\\a\\..", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "\\\\server\\share", name: "\\\\server\\share", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "\\\\server\\share\\a", name: "\\\\server\\share\\a", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "\\\\server\\share\\a\\..", name: "\\\\server\\share\\a\\..", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a\\..\\b", name: "a\\..\\b", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a/..\\b", name: "..\\b", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "..\\a", name: "..\\a", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a\\..", name: "a\\..", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a\\b\\c\\..\\d", name: "a\\b\\c\\..\\d", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "\u00e9", name: "\u00e9", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a/\u00e9", name: "\u00e9", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/b\u00e9c", name: "b\u00e9c", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/", name: "a", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "./x", name: "x", nameOK: true, parent: ".", parentOK: true, wf: "./N.readers"},
		{shape: "x/.", name: "x", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "./.", name: "", nameOK: false, parent: "", parentOK: true, wf: "././N.readers"},
		{shape: ".//x", name: "x", nameOK: true, parent: ".", parentOK: true, wf: "./N.readers"},
		{shape: "x//.", name: "x", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a/b.", name: "b.", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/b..", name: "b..", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/b...", name: "b...", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: ".x", name: ".x", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "..x", name: "..x", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "...x", name: "...x", nameOK: true, parent: "", parentOK: true, wf: "N.readers"},
		{shape: "a/...x", name: "...x", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "x/..x/y", name: "y", nameOK: true, parent: "x/..x", parentOK: true, wf: "x/..x/N.readers"},
		{shape: "a/.//b", name: "b", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a//./b", name: "b", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "/./a", name: "a", nameOK: true, parent: "/", parentOK: true, wf: "/N.readers"},
		{shape: "/..", name: "", nameOK: false, parent: "/", parentOK: true, wf: "/../N.readers"},
		{shape: "/../..", name: "", nameOK: false, parent: "/..", parentOK: true, wf: "/../../N.readers"},
		{shape: "/../a", name: "a", nameOK: true, parent: "/..", parentOK: true, wf: "/../N.readers"},
		{shape: "//a", name: "a", nameOK: true, parent: "/", parentOK: true, wf: "/N.readers"},
		{shape: "///a", name: "a", nameOK: true, parent: "/", parentOK: true, wf: "/N.readers"},
		{shape: "////", name: "", nameOK: false, parent: "", parentOK: false, wf: "////N.readers"},
		{shape: "a/b/./", name: "b", nameOK: true, parent: "a", parentOK: true, wf: "a/N.readers"},
		{shape: "a/b/..//", name: "", nameOK: false, parent: "a/b", parentOK: true, wf: "a/b/..//N.readers"},
		{shape: "./a/b", name: "b", nameOK: true, parent: "./a", parentOK: true, wf: "./a/N.readers"},
		{shape: "../a/b", name: "b", nameOK: true, parent: "../a", parentOK: true, wf: "../a/N.readers"},
		{shape: "../../a/b", name: "b", nameOK: true, parent: "../../a", parentOK: true, wf: "../../a/N.readers"},
		{shape: "a/../../b", name: "b", nameOK: true, parent: "a/../..", parentOK: true, wf: "a/../../N.readers"},
	}
	for _, row := range rows {
		name, nameOK := FileName(row.shape)
		if name != row.name || nameOK != row.nameOK {
			t.Errorf("FileName(%q) = (%q, %v), want (%q, %v)", row.shape, name, nameOK, row.name, row.nameOK)
		}
		parent, parentOK := Parent(row.shape)
		if parent != row.parent || parentOK != row.parentOK {
			t.Errorf("Parent(%q) = (%q, %v), want (%q, %v)", row.shape, parent, parentOK, row.parent, row.parentOK)
		}
		wf := WithFileName(row.shape, "N.readers")
		if wf != row.wf {
			t.Errorf("WithFileName(%q) = %q, want %q", row.shape, wf, row.wf)
		}
	}
}
