//! Frozen generation-1 C ABI numeric registry.

pub const ABI_VERSION: u32 = 1;

pub const STATUS_OK: u32 = 0;
pub const STATUS_ERROR: u32 = 1;

pub const ADDRESS_FAMILY_IPV4: u32 = 4;
pub const ADDRESS_FAMILY_IPV6: u32 = 6;

pub const PATH_POSIX_BYTES: u32 = 1;
pub const PATH_WINDOWS_UTF16: u32 = 2;

pub const VALUE_KIND_DIRECT: u32 = 1;
pub const VALUE_KIND_MEMBERSHIP: u32 = 2;

pub const SOURCE_OUTCOME_BATCH: u32 = 1;
pub const SOURCE_OUTCOME_END: u32 = 2;
pub const SOURCE_OUTCOME_ERROR: u32 = 3;

pub const SINK_OUTCOME_CONTINUE: u32 = 1;
pub const SINK_OUTCOME_STOP: u32 = 2;
pub const SINK_OUTCOME_ERROR: u32 = 3;

pub const CURSOR_DIRECTION_FORWARD: u32 = 1;
pub const CURSOR_DIRECTION_BACKWARD: u32 = 2;

pub const OPEN_MODE_IMMUTABLE: u32 = 1;
pub const OPEN_MODE_LIVE: u32 = 2;
pub const OPEN_MODE_OFFLINE: u32 = 3;

pub const DESTINATION_POLICY_FAIL_IF_EXISTS: u32 = 1;
pub const DESTINATION_POLICY_REPLACE_EXISTING: u32 = 2;
pub const DESTINATION_POLICY_REPLACE_EXISTING_NO_ROLLBACK: u32 = 3;

pub const LIVE_RESET_POLICY_ROLLBACK_SAFE: u32 = 1;
pub const LIVE_RESET_POLICY_DISCARD_PREVIOUS: u32 = 2;

pub const RESOLVER_ACTION_COMPLETE: u32 = 1;
pub const RESOLVER_ACTION_REMOVE: u32 = 2;

pub const MEMBERSHIP_OPERATION_REPLACE: u32 = 1;
pub const MEMBERSHIP_OPERATION_UNION: u32 = 2;
pub const MEMBERSHIP_OPERATION_DIFFERENCE: u32 = 3;
pub const MEMBERSHIP_OPERATION_INTERSECTION: u32 = 4;
pub const MEMBERSHIP_OPERATION_XOR: u32 = 5;

pub const MEMBERSHIP_AGGREGATION_CARDINALITIES: u32 = 1;
pub const MEMBERSHIP_AGGREGATION_ALL_PAIRS: u32 = 2;
pub const MEMBERSHIP_AGGREGATION_TARGET_AGAINST_SCOPE: u32 = 3;
pub const MEMBERSHIP_AGGREGATION_SELECTED_PAIRS: u32 = 4;

pub const UNCOVERED_SIDE_LEFT: u32 = 1;
pub const UNCOVERED_SIDE_RIGHT: u32 = 2;

pub const FEED_SELECTION_ALL: u32 = 1;
pub const FEED_SELECTION_NAMED: u32 = 2;

pub const ALGEBRA_SET_UNION: u32 = 1;
pub const ALGEBRA_SET_INTERSECTION: u32 = 2;
pub const ALGEBRA_SET_EXCLUSION: u32 = 3;

pub const ALGEBRA_OUTPUT_PRESERVE_FEEDS: u32 = 1;
pub const ALGEBRA_OUTPUT_FLAT: u32 = 2;

pub const VALIDATION_MODE_LIVE_CURRENT: u32 = 1;
pub const VALIDATION_MODE_IMMUTABLE_CURRENT: u32 = 2;
pub const VALIDATION_MODE_OFFLINE_CANDIDATE: u32 = 3;

pub const RECOVERY_CANDIDATE_NEWEST: u32 = 1;
pub const RECOVERY_CANDIDATE_PREVIOUS: u32 = 2;
pub const RECOVERY_CANDIDATE_UNORDERED_META0: u32 = 3;
pub const RECOVERY_CANDIDATE_UNORDERED_META1: u32 = 4;

pub const CLEANUP_STATE_CLEAN: u32 = 1;
pub const CLEANUP_STATE_RESIDUE_POSSIBLE: u32 = 2;

pub const COORDINATION_CLEANUP_NONE: u32 = 1;
pub const COORDINATION_CLEANUP_GUARD: u32 = 2;
pub const COORDINATION_CLEANUP_RETAINED_READER_CLOSE_REQUIRED: u32 = 3;
pub const COORDINATION_CLEANUP_RETAINED_WRITER_CLOSE_REQUIRED: u32 = 4;

pub const HOUSEKEEPING_NONE: u32 = 1;
pub const HOUSEKEEPING_CRASH_REAPPEARANCE_POSSIBLE: u32 = 2;
pub const HOUSEKEEPING_VISIBLE: u32 = 3;

pub const WINDOWS_HOUSEKEEPING_TRANSITION_MOVE_PENDING: u32 = 1;
pub const WINDOWS_HOUSEKEEPING_TRANSITION_MOVE_AMBIGUOUS: u32 = 2;
pub const WINDOWS_HOUSEKEEPING_TRANSITION_INERT: u32 = 3;
pub const WINDOWS_HOUSEKEEPING_TRANSITION_CONFLICT: u32 = 4;

pub const ACCESS_ABSENT: u32 = 1;
pub const ACCESS_CREATOR_ONLY: u32 = 2;
pub const ACCESS_CHANGED_OR_UNPROVEN: u32 = 3;
pub const ACCESS_UNCLASSIFIED: u32 = 4;

pub const META_SELECTION_PROVEN_CURRENT: u32 = 1;
pub const META_SELECTION_SOLE_META0: u32 = 2;
pub const META_SELECTION_SOLE_META1: u32 = 3;

pub const COMMIT_DURABILITY_NOT_COMMITTED: u32 = 1;
pub const COMMIT_DURABILITY_COMMITTED: u32 = 2;
pub const COMMIT_DURABILITY_OUTCOME_UNKNOWN: u32 = 3;

pub const CREATION_NOT_CREATED: u32 = 1;
pub const CREATION_CREATED: u32 = 2;
pub const CREATION_OUTCOME_UNKNOWN: u32 = 3;

pub const LIVE_TRANSITION_NOT_INITIALIZED: u32 = 1;
pub const LIVE_TRANSITION_OLD_COORDINATION_RETAINED: u32 = 2;
pub const LIVE_TRANSITION_LEFT_IMMUTABLE: u32 = 3;
pub const LIVE_TRANSITION_INITIALIZED: u32 = 4;
pub const LIVE_TRANSITION_OUTCOME_UNKNOWN: u32 = 5;

pub const PUBLICATION_NOT_PUBLISHED: u32 = 1;
pub const PUBLICATION_PUBLISHED: u32 = 2;
pub const PUBLICATION_OUTCOME_UNKNOWN: u32 = 3;

pub const DESTINATION_CONTENT_DESIRED: u32 = 1;
pub const DESTINATION_CONTENT_PREVIOUS: u32 = 2;
pub const DESTINATION_CONTENT_ABSENT: u32 = 3;
pub const DESTINATION_CONTENT_OTHER: u32 = 4;
pub const DESTINATION_CONTENT_UNCLASSIFIED: u32 = 5;

pub const LATER_CANONICAL_OWNER_NONE: u32 = 1;
pub const LATER_CANONICAL_OWNER_RESERVATION_OR_TRANSITION: u32 = 2;
pub const LATER_CANONICAL_OWNER_READY_LIVE_SIDECAR: u32 = 3;

pub const LIVE_LINEAGE_SAME_GENERATION_EXACT_BYTES: u32 = 1;
pub const LIVE_LINEAGE_SAME_GENERATION_PHYSICAL_BYTES_CHANGED: u32 = 2;
pub const LIVE_LINEAGE_ADVANCED_GENERATION: u32 = 3;

pub const LOCAL_FILE_RELATION_SAME_LOCAL_FILE: u32 = 1;
pub const LOCAL_FILE_RELATION_DIFFERENT_LOCAL_FILE: u32 = 2;

pub const COMMIT_RESOLUTION_COMMITTED: u32 = 1;
pub const COMMIT_RESOLUTION_NOT_COMMITTED: u32 = 2;
pub const COMMIT_RESOLUTION_SUPERSEDED_UNKNOWN: u32 = 3;
pub const COMMIT_RESOLUTION_UNRESOLVABLE: u32 = 4;

pub const ABORT_OUTCOME_ABORTED: u32 = 1;
pub const ABORT_OUTCOME_ABORT_INCOMPLETE: u32 = 2;

pub const CLOSE_OUTCOME_CLOSED: u32 = 1;
pub const CLOSE_OUTCOME_INCOMPLETE: u32 = 2;

pub const LIVE_TRANSITION_OPERATION_INITIALIZE: u32 = 1;
pub const LIVE_TRANSITION_OPERATION_RESET: u32 = 2;

pub const LIVE_COORDINATION_LOCATION_ABSENT: u32 = 1;
pub const LIVE_COORDINATION_LOCATION_CANONICAL: u32 = 2;
pub const LIVE_COORDINATION_LOCATION_PRIVATE: u32 = 3;
pub const LIVE_COORDINATION_LOCATION_UNCLASSIFIED: u32 = 4;

pub const LIVE_RESIDUE_STATUS_ABSENT: u32 = 1;
pub const LIVE_RESIDUE_STATUS_READY: u32 = 2;
pub const LIVE_RESIDUE_STATUS_COMPLETED: u32 = 3;
pub const LIVE_RESIDUE_STATUS_REMOVED: u32 = 4;
pub const LIVE_RESIDUE_STATUS_OUTCOME_UNKNOWN: u32 = 5;

pub const LIVE_RESIDUE_KIND_CANONICAL: u32 = 1;
pub const LIVE_RESIDUE_KIND_PRIVATE_RESET: u32 = 2;

pub const ARTIFACT_KIND_PRIVATE_OUTPUT: u32 = 1;
pub const ARTIFACT_KIND_PRIVATE_RESERVATION: u32 = 2;
pub const ARTIFACT_KIND_OWNED_COORDINATION: u32 = 3;
pub const ARTIFACT_KIND_AUTHORIZED_SCRATCH: u32 = 4;
pub const ARTIFACT_KIND_OWNED_MAIN: u32 = 5;
pub const ARTIFACT_KIND_UNPUBLISHED_MAIN_TAIL: u32 = 6;

pub const ARTIFACT_PRESENCE_ABSENT: u32 = 1;
pub const ARTIFACT_PRESENCE_PRESENT: u32 = 2;
pub const ARTIFACT_PRESENCE_UNCLASSIFIED: u32 = 3;

pub const ARTIFACT_RECORD_KIND_AUTHORIZED_SCRATCH: u32 = 1;
pub const ARTIFACT_RECORD_KIND_PUBLICATION_TEMP: u32 = 2;
pub const ARTIFACT_RECORD_KIND_PUBLICATION_RESERVATION: u32 = 3;

pub const SCRATCH_AUTHENTICATION_UNAUTHENTICATED: u32 = 0;
pub const SCRATCH_AUTHENTICATION_VALIDATION: u32 = 1;
pub const SCRATCH_AUTHENTICATION_RECOVERY: u32 = 2;

pub const ABANDONED_RESERVATION_PHASE_PREPARED: u32 = 1;
pub const ABANDONED_RESERVATION_PHASE_MAIN_MAY_HAVE_BEEN_ATTEMPTED: u32 = 2;

pub const WINDOWS_HOUSEKEEPING_CANDIDATE_ENVELOPE: u32 = 1;
pub const WINDOWS_HOUSEKEEPING_CANDIDATE_INERT_PAYLOAD: u32 = 2;

pub const DIRECTORY_ROLE_DESTINATION: u32 = 1;
pub const DIRECTORY_ROLE_SCRATCH_DIRECTORY: u32 = 2;
pub const DIRECTORY_ROLE_MAIN_FILE: u32 = 3;

pub const LOCAL_IDENTITY_KIND_POSIX: u32 = 1;
pub const LOCAL_IDENTITY_KIND_WINDOWS: u32 = 2;

pub const CREATION_SECURITY_KIND_POSIX: u32 = 1;
pub const CREATION_SECURITY_KIND_WINDOWS: u32 = 2;

pub const OBJECT_KIND_FILE_GEOMETRY: u32 = 1;
pub const OBJECT_KIND_META: u32 = 2;
pub const OBJECT_KIND_RANGE_TREE: u32 = 3;
pub const OBJECT_KIND_CATALOG_NAME_TREE: u32 = 4;
pub const OBJECT_KIND_CATALOG_INDEX_TREE: u32 = 5;
pub const OBJECT_KIND_MEMBERSHIP_DICTIONARY: u32 = 6;
pub const OBJECT_KIND_MEMBERSHIP_REVERSE_INDEX: u32 = 7;
pub const OBJECT_KIND_MEMBERSHIP_BLOB: u32 = 8;
pub const OBJECT_KIND_METADATA: u32 = 9;
pub const OBJECT_KIND_FREE_BITMAP: u32 = 10;
pub const OBJECT_KIND_FEED_USED_BITMAP: u32 = 11;
pub const OBJECT_KIND_MEMBERSHIP_USED_BITMAP: u32 = 12;
pub const OBJECT_KIND_RETIREMENT_TREE: u32 = 13;
pub const OBJECT_KIND_RETIREMENT_BLOB: u32 = 14;

pub const LOGICAL_CHANGE_CHANGED: u32 = 1;
pub const LOGICAL_CHANGE_NO_CHANGE: u32 = 2;

pub const DIRECT_SEMANTIC_NOT_APPLICABLE: u32 = 0;
pub const DIRECT_SEMANTIC_GENERIC: u32 = 1;
pub const DIRECT_SEMANTIC_FIRST_SEEN: u32 = 2;
pub const DIRECT_SEMANTIC_LAST_SEEN: u32 = 3;

pub const WORKFLOW_CREATE_FEED: u32 = 1;
pub const WORKFLOW_REPLACE_FEED: u32 = 2;
pub const WORKFLOW_DIRECT_REPLACEMENT: u32 = 3;
pub const WORKFLOW_FIRST_SEEN_REFRESH: u32 = 4;
pub const WORKFLOW_LAST_SEEN_REFRESH: u32 = 5;
pub const WORKFLOW_MEMBERSHIP_IMPORT: u32 = 6;

pub const REPORT_KIND_SCAN: u32 = 1;
pub const REPORT_KIND_FINISH_INPUT: u32 = 2;
pub const REPORT_KIND_COMMIT: u32 = 3;
pub const REPORT_KIND_COMMIT_RESOLUTION: u32 = 4;
pub const REPORT_KIND_ABORT: u32 = 5;
pub const REPORT_KIND_CLOSE: u32 = 6;
pub const REPORT_KIND_RECLAIM: u32 = 7;
pub const REPORT_KIND_CREATE: u32 = 8;
pub const REPORT_KIND_LIVE_TRANSITION: u32 = 9;
pub const REPORT_KIND_CREATE_RESOLUTION: u32 = 10;
pub const REPORT_KIND_LIVE_TRANSITION_RESOLUTION: u32 = 11;
pub const REPORT_KIND_PUBLICATION: u32 = 12;
pub const REPORT_KIND_VALIDATION: u32 = 13;
pub const REPORT_KIND_RECOVERY_CANDIDATES: u32 = 14;
pub const REPORT_KIND_RECOVERY: u32 = 15;
pub const REPORT_KIND_RESIDUE: u32 = 16;
pub const REPORT_KIND_LIVE_RESIDUE: u32 = 17;
pub const REPORT_KIND_HISTORY_PROJECTION: u32 = 18;

pub const RESIDUE_OPERATION_INSPECT_PUBLICATION: u32 = 1;
pub const RESIDUE_OPERATION_REMOVE_PUBLICATION: u32 = 2;
pub const RESIDUE_OPERATION_LIST_ABANDONED_SCRATCH: u32 = 3;
pub const RESIDUE_OPERATION_REMOVE_ABANDONED_SCRATCH: u32 = 4;
pub const RESIDUE_OPERATION_LIST_ABANDONED_PUBLICATION_TEMPS: u32 = 5;
pub const RESIDUE_OPERATION_REMOVE_ABANDONED_PUBLICATION_TEMP: u32 = 6;
pub const RESIDUE_OPERATION_LIST_ABANDONED_RESERVATION_ARTIFACTS: u32 = 7;
pub const RESIDUE_OPERATION_REMOVE_ABANDONED_RESERVATION_ARTIFACT: u32 = 8;
pub const RESIDUE_OPERATION_LIST_HOUSEKEEPING_ARTIFACTS: u32 = 9;
pub const RESIDUE_OPERATION_REMOVE_HOUSEKEEPING_ARTIFACT: u32 = 10;
pub const RESIDUE_OPERATION_SNAPSHOT_PREPARATION_FAILURE: u32 = 11;
pub const RESIDUE_OPERATION_IMMUTABLE_FEED_PREPARATION_FAILURE: u32 = 12;
pub const RESIDUE_OPERATION_ALGEBRA_PREPARATION_FAILURE: u32 = 13;

pub const RESIDUE_COORDINATION_ABSENT: u32 = 1;
pub const RESIDUE_COORDINATION_PUBLICATION_RESERVATION: u32 = 2;
pub const RESIDUE_COORDINATION_LIVE_SIDECAR: u32 = 3;
pub const RESIDUE_COORDINATION_UNSELECTABLE: u32 = 4;

pub const RESIDUE_MAIN_CONTENT_V4: u32 = 1;
pub const RESIDUE_MAIN_CONTENT_OTHER: u32 = 2;

pub const REASON_META_UNAVAILABLE: u32 = 1;
pub const REASON_META_INVALID: u32 = 2;
pub const REASON_META_STATIC_MISMATCH: u32 = 3;
pub const REASON_FILE_GEOMETRY_INVALID: u32 = 4;
pub const REASON_ROOT_COUNT_INVALID: u32 = 5;
pub const REASON_IO_ERROR: u32 = 6;
pub const REASON_ARITHMETIC_OVERFLOW: u32 = 7;
pub const REASON_PAGE_OUT_OF_BOUNDS: u32 = 8;
pub const REASON_PAGE_HEADER_INVALID: u32 = 9;
pub const REASON_PAGE_CRC_MISMATCH: u32 = 10;
pub const REASON_PAGE_TYPE_MISMATCH: u32 = 11;
pub const REASON_PAGE_BORN_TXN_INVALID: u32 = 12;
pub const REASON_PAGE_RESERVED_NONZERO: u32 = 13;
pub const REASON_TREE_CYCLE: u32 = 14;
pub const REASON_PAGE_ALIAS: u32 = 15;
pub const REASON_TREE_LEVEL_INVALID: u32 = 16;
pub const REASON_TREE_ORDER_INVALID: u32 = 17;
pub const REASON_TREE_FENCE_INVALID: u32 = 18;
pub const REASON_RANGE_REVERSED: u32 = 19;
pub const REASON_RANGE_OVERLAP: u32 = 20;
pub const REASON_RANGE_NOT_COALESCED: u32 = 21;
pub const REASON_CATALOG_NAME_INVALID: u32 = 22;
pub const REASON_CATALOG_BIJECTION_INVALID: u32 = 23;
pub const REASON_CATALOG_BITMAP_INVALID: u32 = 24;
pub const REASON_MEMBERSHIP_BITMAP_INVALID: u32 = 25;
pub const REASON_MEMBERSHIP_HASH_INVALID: u32 = 26;
pub const REASON_MEMBERSHIP_REVERSE_INDEX_INVALID: u32 = 27;
pub const REASON_MEMBERSHIP_REFCOUNT_INVALID: u32 = 28;
pub const REASON_MEMBERSHIP_ACTIVE_FEED_INVALID: u32 = 29;
pub const REASON_BLOB_INVALID: u32 = 30;
pub const REASON_METADATA_ZLIB_INVALID: u32 = 31;
pub const REASON_METADATA_LENGTH_INVALID: u32 = 32;
pub const REASON_BITMAP_SUMMARY_INVALID: u32 = 33;
pub const REASON_ALLOCATION_PARTITION_INVALID: u32 = 34;
pub const REASON_RETIREMENT_ORDER_INVALID: u32 = 35;
pub const REASON_RETIREMENT_LIST_INVALID: u32 = 36;
pub const REASON_CATALOG_INVALID: u32 = 37;
pub const REASON_MEMBERSHIP_MISSING: u32 = 38;
pub const REASON_MEMBERSHIP_INVALID: u32 = 39;
pub const REASON_METADATA_INVALID: u32 = 40;

pub const ERROR_CODE_INVALID_ARGUMENT: u32 = 1;
pub const ERROR_CODE_NULL_POINTER: u32 = 2;
pub const ERROR_CODE_MISALIGNED_POINTER: u32 = 3;
pub const ERROR_CODE_INVALID_LENGTH: u32 = 4;
pub const ERROR_CODE_INVALID_ENUM: u32 = 5;
pub const ERROR_CODE_RESERVED_NONZERO: u32 = 6;
pub const ERROR_CODE_BUFFER_TOO_SMALL: u32 = 7;
pub const ERROR_CODE_WRONG_HANDLE_KIND: u32 = 8;
pub const ERROR_CODE_HANDLE_CLOSED: u32 = 9;
pub const ERROR_CODE_HANDLE_BUSY: u32 = 10;
pub const ERROR_CODE_WRONG_STATE: u32 = 11;
pub const ERROR_CODE_WRONG_ADDRESS_FAMILY: u32 = 12;
pub const ERROR_CODE_WRONG_VALUE_KIND: u32 = 13;
pub const ERROR_CODE_WRONG_VALUE_TAG: u32 = 14;
pub const ERROR_CODE_RANGE_REVERSED: u32 = 15;
pub const ERROR_CODE_NAME_INVALID: u32 = 16;
pub const ERROR_CODE_NAME_EXISTS: u32 = 17;
pub const ERROR_CODE_NAME_NOT_FOUND: u32 = 18;
pub const ERROR_CODE_STALE_REFERENCE: u32 = 19;
pub const ERROR_CODE_FOREIGN_REFERENCE: u32 = 20;
pub const ERROR_CODE_NO_PENDING_TRANSACTION: u32 = 21;
pub const ERROR_CODE_TRANSACTION_ABORTED: u32 = 22;
pub const ERROR_CODE_ABORT_INCOMPLETE: u32 = 23;
pub const ERROR_CODE_INSUFFICIENT_RESOURCE_BUDGET: u32 = 24;
pub const ERROR_CODE_PAGE_SPACE_EXHAUSTED: u32 = 25;
pub const ERROR_CODE_WORK_LIMIT_TOO_SMALL: u32 = 26;
pub const ERROR_CODE_CANCELLED: u32 = 27;
pub const ERROR_CODE_SOURCE_FAILED: u32 = 28;
pub const ERROR_CODE_SINK_FAILED: u32 = 29;
pub const ERROR_CODE_STOPPED_BY_SINK: u32 = 30;
pub const ERROR_CODE_IO: u32 = 31;
pub const ERROR_CODE_FORMAT_INVALID: u32 = 32;
pub const ERROR_CODE_NOT_V4: u32 = 33;
pub const ERROR_CODE_DURABILITY_UNSUPPORTED: u32 = 34;
pub const ERROR_CODE_PUBLICATION_UNSUPPORTED: u32 = 35;
pub const ERROR_CODE_ACCESS_POLICY_UNSUPPORTED: u32 = 36;
pub const ERROR_CODE_CONFLICT: u32 = 37;
pub const ERROR_CODE_UNRESOLVABLE: u32 = 38;
pub const ERROR_CODE_WRITER_BUSY: u32 = 39;
pub const ERROR_CODE_DIRECTORY_IDENTITY_MISMATCH: u32 = 40;
pub const ERROR_CODE_DESTINATION_NAME_MISMATCH: u32 = 41;
pub const ERROR_CODE_CLEANUP_CONFLICT: u32 = 42;
pub const ERROR_CODE_COORDINATION_SEQUENCE_EXHAUSTED: u32 = 43;
pub const ERROR_CODE_LIVE_COORDINATION_UNSUPPORTED: u32 = 44;
pub const ERROR_CODE_LIVE_COORDINATION_CLEANUP_REQUIRED: u32 = 45;
pub const ERROR_CODE_LIVE_COORDINATION_MALFORMED_REQUIRES_RESET: u32 = 46;
pub const ERROR_CODE_LIVE_OPEN_CLEANUP_REQUIRED: u32 = 47;
pub const ERROR_CODE_LIVE_RECOVERY_COORDINATION_UNAVAILABLE: u32 = 48;
pub const ERROR_CODE_LIVE_RECOVERY_CURRENT_GENERATION_UNPROVABLE: u32 = 49;
pub const ERROR_CODE_LIVE_RECOVERY_CURRENT_GENERATION_UNREADABLE: u32 = 50;
pub const ERROR_CODE_RECOVERY_CANDIDATE_CHANGED: u32 = 51;
pub const ERROR_CODE_RECOVERY_PREPARATION_FAILED: u32 = 52;
pub const ERROR_CODE_SNAPSHOT_PREPARATION_FAILED: u32 = 53;
pub const ERROR_CODE_TRANSITION_SUPERSEDED: u32 = 54;
pub const ERROR_CODE_CURRENT_GENERATION_UNPROVABLE: u32 = 55;
pub const ERROR_CODE_FORKED_HANDLE: u32 = 56;
pub const ERROR_CODE_PANIC: u32 = 57;
pub const ERROR_CODE_OS_UNSUPPORTED: u32 = 58;
pub const ERROR_CODE_TRANSACTION_ID_EXHAUSTED: u32 = 59;
pub const ERROR_CODE_ARITHMETIC_OVERFLOW: u32 = 60;
pub const ERROR_CODE_FEED_INDEX_EXHAUSTED: u32 = 61;
pub const ERROR_CODE_MEMBERSHIP_ID_EXHAUSTED: u32 = 62;
pub const ERROR_CODE_READER_CAPACITY_EXHAUSTED: u32 = 63;
pub const ERROR_CODE_CLEANUP_IN_PROGRESS: u32 = 64;
