[package]
name = "iprange-livedb"
version = "0.0.0"
description = "Rust SDK for the iprange v4 database format"
autobenches = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
flate2 = { version = "=1.1.9", default-features = false, features = ["rust_backend"] }
getrandom = { version = "=0.3.4", features = ["std"] }
libc = "0.2.186"
sha2 = "=0.10.9"
