name: Scorecard

on:
  branch_protection_rule:
  push:
    branches: [master]
  schedule:
    - cron: '39 1 * * 3'
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    name: OpenSSF Scorecard
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Run Scorecard
        uses: ossf/scorecard-action@99c09fe975337306107572b4fdf4db224cf8e2f2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload Scorecard artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: scorecard-sarif
          path: results.sarif
          retention-days: 14

      - name: Upload Scorecard to code scanning
        uses: github/codeql-action/upload-sarif@87557b9c84dde89fdd9b10e88954ac2f4248e463
        with:
          sarif_file: results.sarif
